"""Pydantic models for the NFHL, one per modelled service layer.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from nfhl.models.base_flood_elevations import BaseFloodElevation
from nfhl.models.flood_hazard_zones import FloodHazardZone

__all__ = ["BaseFloodElevation", "FloodHazardZone"]
