"""`S_BFE`: Base Flood Elevations.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import float64, int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.annotations import DatumIn, UnitIn
from nfhl.constraints import drop_null_encodings
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    LengthUnits,
    VDatum,
)


class BaseFloodElevation(Feature):
    """The S_BFE contains information about the BFEs within a Flood Risk Project area.
    A spatial file with location information also corresponds with this data table.
    The spatial elements representing BFE features are lines extending from Special
    Flood Hazard Area (SFHA) boundary to SFHA boundary. The ends of the BFE lines
    must be snapped precisely to the SFHA boundary. Each BFE is represented by a
    single line with no pseudo-nodes. Where BFE lines are shown, they must be
    consistent with procedures described in the FIRM Panel Technical Reference.
    Published as layer 16 of the NFHL MapServer, which also carries `GFID`,
    `GlobalID`, `OBJECTID`, `SHAPE.STLength()`; the reference does not define them,
    so they are optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # “Each BFE is represented by a single line with no pseudo-nodes”, so a LineString,
    # though the service's polyline type admits several parts.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.LINE_STRING),
        Field(
            description=(
                "The BFE line: in the reference's words, a single line extending from "
                "Special Flood Hazard Area (SFHA) boundary to SFHA boundary."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is BFE_LN_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single-jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code, and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    bfe_ln_id: Annotated[str, MaxLen(32)] = Field(
        alias="BFE_LN_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    elev: Annotated[float64, UnitIn("LEN_UNIT"), DatumIn("V_DATUM")] = Field(
        alias="ELEV",
        description=(
            "The rounded, whole-foot elevation of the 1% annual-chance flood. This "
            "is the value of the BFE that is printed next to the BFE line on the "
            "FIRM."
        ),
    )

    len_unit: LengthUnits = Field(
        alias="LEN_UNIT",
        description=(
            "BFE Units. This unit indicates the measurement system used for the "
            "BFEs. Normally this would be feet. Acceptable values for this field "
            "are listed in the D_Length_Units table."
        ),
    )

    v_datum: VDatum = Field(
        alias="V_DATUM",
        description=(
            "Vertical Datum. The vertical datum indicates the reference surface "
            "from which the flood elevations are measured. Normally this would be "
            "North American Vertical Datum of 1988 for new studies. Acceptable "
            "values for this field are listed in the D_V_Datum table."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_stlength: Omitable[float64] = Field(
        alias="SHAPE.STLength()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
