"""`S_XS`: Cross-Sections.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import float64, int16, int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.annotations import DatumIn, UnitIn
from nfhl.constraints import NoneOf, drop_null_encodings, forbid_if
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    LengthUnits,
    VDatum,
    XSLnTyp,
)


# “This field is populated when the cross section is lettered.”
@forbid_if(["xs_ltr"], NoneOf("xs_ln_typ", (XSLnTyp.LETTERED_MAPPED,)))
class CrossSection(Feature):
    """The S_XS table contains information about cross section lines. This information
    is used in the Floodway Data Tables in the FIS Report, as well as on the FIRM
    panels. Database attributes should reflect the final regulatory water surface
    elevations that include any backwater elevations regardless of flood hazard zone
    and should be consistent with values in the floodway data tables and flood
    profiles, where applicable. All cross sections – modeled or interpolated – must
    be stored in the S_XS, regardless of whether or not they are shown on the FIRM
    and regardless of the flood hazard zone ultimately depicted on the effective
    panels. Refer to the Guidance Document No. 31, Guidance for Flood Risk Analysis
    and Mapping: Mapping Base Flood Elevations on Flood Insurance Rate Maps for
    additional information about BFE and cross section placement and labeling
    elevation values on the FIRM panels. The spatial entities representing cross
    sections are lines. Published as layer 14 of the NFHL MapServer, which also
    carries `GFID`, `GlobalID`, `OBJECTID`, `SHAPE.STLength()`; the reference does
    not define them, so they are optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # “The spatial entities representing cross sections are lines”, one to a feature:
    # Table 4 holds S_XS to “Must Be Single Part”, so a LineString.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.LINE_STRING),
        Field(
            description=(
                "The cross section line: in the reference's words, the spatial entities"
                " representing cross sections are lines."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is XS_LN_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single-jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    xs_ln_id: Annotated[str, MaxLen(32)] = Field(
        alias="XS_LN_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    wtr_nm: Annotated[str, MaxLen(100)] = Field(
        alias="WTR_NM",
        description=(
            "Surface Water Feature Name. This is the name of the stream or water body."
        ),
    )

    stream_stn: float64 = Field(
        alias="STREAM_STN",
        description=(
            "Stream Station. This is the measurement along the profile baseline to "
            "the cross section location. This value is used in the FDTs and "
            "profiles."
        ),
    )

    # Length 32 on the service; the reference says 25.
    start_id: Annotated[str, MaxLen(32)] = Field(
        alias="START_ID",
        description=(
            "Station Start Identification. This is the foreign key to the "
            "S_Stn_Start layer. The station start describes the origin for the "
            "measurements in the STREAM_STN field. This value is used in the FDTs "
            "and profiles."
        ),
    )

    xs_ltr: Omitable[Annotated[str, MaxLen(12)]] = Field(
        alias="XS_LTR",
        description=(
            "Cross Section Letter. This is the letter or number that is assigned to"
            " the cross section on the hardcopy FIRM and in the FIS Report. This "
            "field is populated when the cross section is lettered."
        ),
    )

    xs_ln_typ: XSLnTyp = Field(
        alias="XS_LN_TYP",
        description=(
            "Cross-Section Line Type. This attribute should contain ‘LETTERED, "
            "MAPPED’ for cross sections that are shown on the hardcopy FIRM and are"
            " given a letter. If the cross section will be shown on the FIRM but "
            "not lettered, the attribute should contain ‘NOT LETTERED, MAPPED’ to "
            "indicate that it is a cross section shown on the hardcopy FIRM, but "
            "not on the FDTs or profiles. If the cross section will not be shown on"
            " the hardcopy FIRM, this attribute should contain ‘NOT LETTERED, NOT "
            "MAPPED’ to indicate that the cross section is part of the backup data "
            "for the Flood Risk Project but is not shown on the FIRM. All cross "
            "sections used in the development of effective hydraulic models shall "
            "be stored in this table, regardless of the flood hazard zone depicted "
            "on the effective panels. Acceptable values for this field are listed "
            "in the D_XS_Ln_Typ table."
        ),
    )

    wsel_reg: Annotated[float64, UnitIn("LEN_UNIT"), DatumIn("V_DATUM")] = Field(
        alias="WSEL_REG",
        description=(
            "Regulatory Water Surface Elevation for the 1% annual-chance Flood "
            "Event. This is the regulatory water-surface elevation for the 1% "
            "annual-chance flood event in the stream channel at this cross section,"
            " this should include backwater elevations. In the case of levee(s) "
            "associated with a cross section, it is assumed that the levee(s) "
            "holds. For cross sections in the coastal floodplain, this value should"
            " be coded “-8888”. For cross sections in the combined coastal and "
            "riverine floodplain, this value should reflect the results of the "
            "combined rate of occurrence analysis. For cross sections at "
            "confluences where a single water surface elevation cannot be "
            "determined this value should be coded as “-8888”. This field is stored"
            " here and in L_XS_Elev to simplify annotation of the FIRM panel "
            "water-surface elevation at this cross section. This value and the "
            "corresponding value in L_XS_Elev should match."
        ),
    )

    strmbed_el: Annotated[float64, UnitIn("LEN_UNIT"), DatumIn("V_DATUM")] = Field(
        alias="STRMBED_EL",
        description=(
            "Streambed Elevation. This is the water-surface elevation for the "
            "thalweg or the lowest point in the main channel. This value is used in"
            " the profiles."
        ),
    )

    len_unit: LengthUnits = Field(
        alias="LEN_UNIT",
        description=(
            "Water-Surface and Streambed Elevation Units. This unit indicates the "
            "measurement system used for the water-surface and streambed "
            "elevations. Normally, this would be feet. Acceptable values for this "
            "field are listed in the D_Length_Units table."
        ),
    )

    v_datum: VDatum = Field(
        alias="V_DATUM",
        description=(
            "Vertical Datum. The vertical datum indicates the reference surface "
            "from which the flood and streambed elevations are measured. Normally, "
            "this would be NAVD88. Acceptable values for this field are listed in "
            "the D_V_Datum table."
        ),
    )

    profxs_txt: Omitable[Annotated[str, MaxLen(80)]] = Field(
        alias="PROFXS_TXT",
        description=(
            "Profile Cross Section Text. This field stores user-defined cross "
            "section text that is plotted on the profile. This field is only "
            "required to be populated if and when the data can be exported from "
            "RASPLOT in FIRM Database Technical Reference format."
        ),
    )

    # Length 107 on the service; the reference says 100.
    model_id: Annotated[str, MaxLen(107)] = Field(
        alias="MODEL_ID",
        description=(
            "Model Identifier. This field stores the feature’s identifier that was "
            "used during hydrologic and hydraulic modeling. This field provides a "
            "link between the hydrologic or hydraulic modeling and this spatial "
            "file. This field should be populated with the name of the of the "
            "submitted model, Ex: River_Run.prj"
        ),
    )

    seq: Omitable[int16] = Field(
        alias="SEQ",
        description=(
            "Sequence. This is the order in which the cross sections plot on the "
            "profile. This value is needed for profiles. This field is only "
            "required if and when the data can be exported from RASPLOT in FIRM "
            "Database Technical Reference format."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_stlength: Omitable[float64] = Field(
        alias="SHAPE.STLength()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
