"""Coded-value domains from the Domain Tables Technical Reference.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.

Each member's value is the text the NFHL stores, unchanged: the
reference's FIRM description, not its coded value. The service, the
state file geodatabases and the county shapefiles all hold that text
and declare no coded-value domains. Each member's description says
what the value means, from the reference, and gives its coded value.

Members whose description begins `Legacy:` are values the reference
does not list but the data commonly holds (spec/legacy.json). They
validate, and the models raise a `nfhl.legacy.LegacyValueWarning`.
"""

from __future__ import annotations

from enum import Enum

from overture.schema.system.doc import DocumentedEnum

REFERENCE_EDITION = "November 2024"


class LengthUnits(str, DocumentedEnum):
    """Values of `D_Length_Units` that apply to the FIRM Database, each as the data
    stores it. Used by `S_Fld_Haz_Ar.LEN_UNIT`.
    """

    CENTIMETERS = "Centimeters", "Coded value `CM`."
    FEET = "Feet", "Coded value `FT`."
    INCHES = "Inches", "Coded value `IN`."
    KILOMETERS = "Kilometers", "Coded value `KM`."
    METERS = "Meters", "Coded value `M`."
    MILES = "Miles", "Coded value `MI`."
    MILLIMETERS = "Millimeters", "Coded value `MM`."
    U_S_SURVEY_FEET = "U.S. Survey Feet", "Coded value `USFT`."
    NP = "NP", "Coded value `NP`."


class StudyTyp(str, DocumentedEnum):
    """Values of `D_Study_Typ` that apply to the FIRM Database, each as the data stores
    it. Used by `S_Fld_Haz_Ar.STUDY_TYP`. The last 7 are legacy values: common in
    the data, not in the reference.
    """

    BLE_AVAILABLE_BUT_UNPUBLISHED = (
        "BLE available but unpublished",
        (
            "Base Level Engineering data are available, but zones and Baseflood "
            "Elevations (BFEs) are not published on FIRM. Coded value `1030`."
        ),
    )
    SFHA_WITHOUT_BFE = (
        "SFHA without BFE",
        (
            "Such as A zones without BFEs or water surface elevations. Coded value "
            "`1000`."
        ),
    )
    SFHA_WITH_UNPUBLISHED_BFE = (
        "SFHA with unpublished BFE",
        (
            "Such as A zones with BFEs or water surface elevations calculated but "
            "not published in FIS Report. Coded value `1040`."
        ),
    )
    SFHA_WITH_BFE_PUBLISHED_ONLY_IN_FIS = (
        "SFHA with BFE published only in FIS",
        (
            "Such as A zones with BFEs or water surface elevations published only "
            "in FIS Report. Coded value `1010`."
        ),
    )
    SFHA_WITH_BFE_NO_FLOODWAY = (
        "SFHA with BFE no floodway",
        (
            "Such as AE or VE zones with regulatory water surface elevations or "
            "depths but no floodway; or shaded-X zones that are associated with "
            "this type of study. Coded value `1050`."
        ),
    )
    SFHA_WITH_BFE_AND_FLOODWAY = (
        "SFHA with BFE and floodway",
        (
            "Such as AE or VE zones with regulatory water surface elevations and a "
            "regulatory floodway; or shaded-X zones that are associated with this "
            "type of study. Coded value `1060`."
        ),
    )
    SHADED_ZONE_X_WITH_DEPTHS_LESS_THAN_1 = (
        "Shaded Zone X with depths less than 1’",
        "Such as Zone X with depths less than 1’. Coded value `1070`.",
    )
    NP = "NP", "NP; unshaded-X zones. Coded value `NP`."
    SFHAS_WITH_LOW_FLOOD_RISK = (
        "SFHAs WITH LOW FLOOD RISK",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. One of three study types graded "
            "by flood risk (LOW, MEDIUM, HIGH) that the 2024 reference does not "
            "list. Which edition defined them is unverified. Held by 979,594 of "
            "5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    SFHAS_WITH_HIGH_FLOOD_RISK = (
        "SFHAs WITH HIGH FLOOD RISK",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. One of three study types graded "
            "by flood risk (LOW, MEDIUM, HIGH) that the 2024 reference does not "
            "list. Which edition defined them is unverified. Held by 557,235 of "
            "5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    SFHAS_WITH_MEDIUM_FLOOD_RISK = (
        "SFHAs WITH MEDIUM FLOOD RISK",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. One of three study types graded "
            "by flood risk (LOW, MEDIUM, HIGH) that the 2024 reference does not "
            "list. Which edition defined them is unverified. Held by 193,351 of "
            "5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    REDELINEATION = (
        "REDELINEATION",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. A study type naming how the map "
            "was made, which the 2024 reference does not list. Which edition "
            "defined it is unverified. Held by 72,844 of 5,810,832 rows of "
            "`STUDY_TYP` on NFHL service layer 28, counted 2026-10-05."
        ),
    )
    SHADED_ZONE_X_WITH_DEPTHS_LESS_THAN_1_LEGACY = (
        "Shaded Zone X with depths less than 1'",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. Coded value 1070, `Shaded Zone X "
            "with depths less than 1’`, written with an ASCII apostrophe where the "
            "reference prints a typographic one. More rows hold this form (33,992) "
            "than the reference's (10,645). Held by 33,992 of 5,810,832 rows of "
            "`STUDY_TYP` on NFHL service layer 28, counted 2026-10-05."
        ),
    )
    DIGITAL_CONVERSION = (
        "DIGITAL CONVERSION",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. A study type naming how the map "
            "was made, which the 2024 reference does not list. Which edition "
            "defined it is unverified. Held by 12,946 of 5,810,832 rows of "
            "`STUDY_TYP` on NFHL service layer 28, counted 2026-10-05."
        ),
    )
    SPECIAL_FLOOD_HAZARD_AREA_SFHA_WITHO = (
        "Special Flood Hazard Area (SFHA) witho",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. Cut off at the field's 38 "
            "characters. The full value is not recoverable from the data, and the "
            "2024 reference has no study type that begins this way. Held by 6,493 "
            "of 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )


class TrueFalse(str, DocumentedEnum):
    """Values of `D_TrueFalse` that apply to the FIRM Database, each as the data stores
    it. Used by `S_Fld_Haz_Ar.SFHA_TF`, `S_Fld_Haz_Ar.DUAL_ZONE`.
    """

    T = "T", "True (Yes). Coded value `T`."
    F = "F", "False (No). Coded value `F`."
    U = "U", "Unknown. Coded value `U`."


class VDatum(str, DocumentedEnum):
    """Values of `D_V_Datum` that apply to the FIRM Database, each as the data stores
    it. Used by `S_Fld_Haz_Ar.V_DATUM`.
    """

    MSL = "MSL", "Mean Sea Level. Coded value `MSL`."
    NAVD88 = "NAVD88", "North American Vertical Datum 1988. Coded value `NAVD88`."
    NGVD29 = (
        "NGVD29",
        "North American Geodetic Vertical Datum 1929. Coded value `NGVD29`.",
    )
    LOCAL_TIDAL_DATUM = "LOCAL TIDAL DATUM", "Local Tidal Datum. Coded value `TIDAL`."
    MLLW = "MLLW", "Mean Lower Low Water Datum. Coded value `MLLW`."
    MLW = "MLW", "Mean Low Water Datum. Coded value `MLW`."
    GUVD04 = "GUVD04", "Guam Vertical Datum of 2004. Coded value `GUVD04`."
    NMVD03 = "NMVD03", "Northern Marianas Vertical Datum of 2003. Coded value `NMVD03`."
    PRVD02 = "PRVD02", "Puerto Rico Vertical Datum of 2002. Coded value `PRVD02`."
    VIVD09 = "VIVD09", "Virgin Islands Vertical Datum of 2009. Coded value `VIVD09`."
    NP = "NP", "Coded value `NP`."


class VelocityUnits(str, DocumentedEnum):
    """Values of `D_Velocity_Units` that apply to the FIRM Database, each as the data
    stores it. Used by `S_Fld_Haz_Ar.VEL_UNIT`.
    """

    CENTIMETERS_DAY = "Centimeters / Day", "Coded value `1000`."
    CENTIMETERS_HOUR = "Centimeters / Hour", "Coded value `1010`."
    FEET_SECOND = "Feet / Second", "Coded value `1020`."
    INCHES_DAY = "Inches / Day", "Coded value `1030`."
    INCHES_HOUR = "Inches / Hour", "Coded value `1040`."
    METERS_SECOND = "Meters / Second", "Coded value `1050`."
    MICROMETERS_SECOND = "Micrometers / Second", "Coded value `1060`."
    MILLIMETERS_DAY = "Millimeters / Day", "Coded value `1070`."
    MILLIMETERS_HOUR = "Millimeters / Hour", "Coded value `1080`."
    NP = "NP", "Coded value `NP`."


class Zone(str, DocumentedEnum):
    """Values of `D_Zone` that apply to the FIRM Database, each as the data stores it.
    Used by `S_Fld_Haz_Ar.FLD_ZONE`, `S_Fld_Haz_Ar.AR_REVERT`.
    """

    A = "A", "Coded value `A`."
    A99 = "A99", "Coded value `A99`."
    AE = "AE", "Coded value `AE`."
    AH = "AH", "Coded value `AH`."
    AO = "AO", "Coded value `AO`."
    AR = "AR", "Coded value `AR`."
    AREA_NOT_INCLUDED = "AREA NOT INCLUDED", "Coded value `ANI`."
    D = "D", "Coded value `D`."
    OPEN_WATER = "OPEN WATER", "Coded value `OW`."
    V = "V", "Coded value `V`."
    VE = "VE", "Coded value `VE`."
    X = "X", "Coded value `X`."


class ZoneSubtype(str, DocumentedEnum):
    """Values of `D_Zone_Subtype` that apply to the FIRM Database, each as the data
    stores it. Used by `S_Fld_Haz_Ar.ZONE_SUBTY`, `S_Fld_Haz_Ar.AR_SUBTRV`. The last
    is a legacy value: common in the data, not in the reference.
    """

    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Coded value `0500`. Printed in the reference"
            " as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN CHANNEL",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. These subtypes are typically symbolized as "
            "shaded Zone X. “1-PCT FUTURE CONDITIONS” is a subtype of Zone X and "
            "are labeled ZONE X FUTURE on the FIRM panel. Coded value `0520`. "
            "Printed in the reference as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD "
            "CONTAINED IN CHANNEL`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. These subtypes are typically symbolized as "
            "shaded Zone X. “1-PCT FUTURE CONDITIONS” is a subtype of Zone X and "
            "are labeled ZONE X FUTURE on the FIRM panel. Coded value `0510`. "
            "Printed in the reference as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD "
            "CONTAINED IN STRUCTURE`."
        ),
    )
    V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL = (
        "1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN CHANNEL",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Coded value `0210`. Printed in the "
            "reference as `1-PCT-ANNUAL-CHANCE FLOOD HAZARD CONTAINED IN CHANNEL`."
        ),
    )
    V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE = (
        "1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Coded value `0200`. Printed in the "
            "reference as `1-PCT-ANNUAL-CHANCE FLOOD HAZARD CONTAINED IN "
            "STRUCTURE`."
        ),
    )
    V_1_PCT_DEPTH_LESS_THAN_1_FOOT = (
        "1 PCT DEPTH LESS THAN 1 FOOT",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Coded value `0400`. Printed in the reference"
            " as `1-PCT DEPTH LESS THAN 1 FOOT`."
        ),
    )
    V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE = (
        "1 PCT DRAINAGE AREA LESS THAN 1 SQUARE MILE",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Coded value `0410`. Printed in the reference"
            " as `1-PCT DRAINAGE AREA LESS THAN 1 SQUARE MILE`."
        ),
    )
    V_1_PCT_FUTURE_CONDITIONS = (
        "1 PCT FUTURE CONDITIONS",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Coded value `0300`. Printed in the reference"
            " as `1-PCT FUTURE CONDITIONS`."
        ),
    )
    V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE = (
        "1 PCT FUTURE CONDITIONS CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. These subtypes are typically symbolized as "
            "shaded Zone X. “1-PCT FUTURE CONDITIONS” is a subtype of Zone X and "
            "are labeled ZONE X FUTURE on the FIRM panel. Coded value `0310`. "
            "Printed in the reference as `1-PCT FUTURE CONDITIONS CONTAINED IN "
            "STRUCTURE`."
        ),
    )
    ADMINISTRATIVE_FLOODWAY = (
        "ADMINISTRATIVE FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1010`."
        ),
    )
    AREA_OF_SPECIAL_CONSIDERATION = (
        "AREA OF SPECIAL CONSIDERATION",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1020`."
        ),
    )
    AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH REDUCED FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE SYSTEM",
        "Formerly “PROTECTED BY LEVEE.” Coded value `1000`.",
    )
    AREA_OF_MINIMAL_FLOOD_HAZARD = (
        "AREA OF MINIMAL FLOOD HAZARD",
        (
            "“AREA OF MINIMAL FLOOD HAZARD” terminology is used by Title 44 Code of"
            " Federal Regulations Section 64.3 to define an unshaded Zone X. Coded "
            "value `2000`."
        ),
    )
    COLORADO_RIVER_FLOODWAY = (
        "COLORADO RIVER FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1040`."
        ),
    )
    COMMUNITY_ENCROACHMENT_AREA = (
        "COMMUNITY ENCROACHMENT AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1030`."
        ),
    )
    DENSITY_FRINGE_AREA = (
        "DENSITY FRINGE AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. "
            "“DENSITY FRINGE AREAS” are a floodway type specific to the State of "
            "Washington used in communities where encroachment and storage-volume "
            "reduction are specified in locations of zoned development, as opposed "
            "to the traditional equal conveyance reduction floodway. Coded value "
            "`1050`."
        ),
    )
    FLOODWAY = (
        "FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1100`."
        ),
    )
    FLOODWAY_CONTAINED_IN_STRUCTURE = (
        "FLOODWAY CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Coded value `1110`."
        ),
    )
    FLOODWAY_CONTAINED_IN_CHANNEL = (
        "FLOODWAY CONTAINED IN CHANNEL",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Coded value `1120`."
        ),
    )
    FLOWAGE_EASEMENT_AREA = (
        "FLOWAGE EASEMENT AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1200`."
        ),
    )
    NARROW_FLOODWAY = (
        "NARROW FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1230`."
        ),
    )
    RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE = (
        "RIVERINE FLOODWAY SHOWN IN COASTAL ZONE",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. These"
            " subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `1220`."
        ),
    )
    STATE_ENCROACHMENT_AREA = (
        "STATE ENCROACHMENT AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Coded"
            " value `1210`."
        ),
    )
    COASTAL_FLOODPLAIN = (
        "COASTAL FLOODPLAIN",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `0100`."
        ),
    )
    COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN = (
        "COMBINED RIVERINE AND COASTAL FLOODPLAIN",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `0120`."
        ),
    )
    RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE = (
        "RIVERINE FLOODPLAIN IN COASTAL ZONE",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `0110`."
        ),
    )
    RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE = (
        "RIVERINE FLOODWAY IN COMBINED RIVERINE AND COASTAL ZONE",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `1240`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD IN COASTAL ZONE",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `0530`. Printed in the "
            "reference as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD IN COASTAL ZONE`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE = (
        ("0.2 PCT ANNUAL CHANCE FLOOD HAZARD IN COMBINED RIVERINE AND COASTAL ZONE"),
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Coded value `0540`. Printed in the "
            "reference as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD IN COMBINED RIVERINE "
            "AND COASTAL ZONE`."
        ),
    )
    AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE SYSTEM",
        "Coded value `3000`.",
    )
    AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM = (
        ("AREA WITH REDUCED FLOOD HAZARD DUE TO PROVISIONALLY ACCREDITED LEVEE SYSTEM"),
        "Coded value `3010`.",
    )
    AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH UNDETERMINED FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE SYSTEM",
        (
            "This subtype is only used in levee impacted areas with a Zone D from "
            "implementing the Analysis and Mapping Procedures for Non-Accredited "
            "Levee Systems. More information on these procedures can be found in "
            "the Levee Guidance document. Coded value `3020`."
        ),
    )
    AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH REDUCED FLOOD HAZARD DUE TO ACCREDITED LEVEE SYSTEM",
        "Coded value `3030`.",
    )
    AREA_WITH_REDUCED_FLOOD_RISK_DUE_TO_LEVEE = (
        "AREA WITH REDUCED FLOOD RISK DUE TO LEVEE",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. An older wording of a levee "
            "subtype: the 2024 subtypes say FLOOD HAZARD and LEVEE SYSTEM, and the "
            "reference does not say which of them this one became. Held by 24,849 "
            "of 5,810,832 rows of `ZONE_SUBTY` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )


# Members the reference does not list; each use raises a warning.
LEGACY_MEMBERS: frozenset[Enum] = frozenset(
    {
        StudyTyp.SFHAS_WITH_LOW_FLOOD_RISK,
        StudyTyp.SFHAS_WITH_HIGH_FLOOD_RISK,
        StudyTyp.SFHAS_WITH_MEDIUM_FLOOD_RISK,
        StudyTyp.REDELINEATION,
        StudyTyp.SHADED_ZONE_X_WITH_DEPTHS_LESS_THAN_1_LEGACY,
        StudyTyp.DIGITAL_CONVERSION,
        StudyTyp.SPECIAL_FLOOD_HAZARD_AREA_SFHA_WITHO,
        ZoneSubtype.AREA_WITH_REDUCED_FLOOD_RISK_DUE_TO_LEVEE,
    }
)
