"""Coded-value domains from the Domain Tables Technical Reference.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.

Each member's value is the text the NFHL stores, unchanged: the
reference's FIRM description, not its code. The service, the
state file geodatabases and the county shapefiles all hold that text
and declare no coded-value domains. Each member's description says
what the value means, from the reference, and its code.

Members whose description begins `Legacy:` are values the reference
does not list but the data commonly holds (spec/legacy.json). They
validate, and the models raise a `nfhl.legacy.LegacyValueWarning`.
"""

from __future__ import annotations

from enum import Enum

from overture.schema.system.doc import DocumentedEnum

REFERENCE_EDITION = "November 2024"


class LengthUnits(str, DocumentedEnum):
    """Values of `D_Length_Units` that apply to the FIRM Database, each as the data
    stores it. Used by `S_Fld_Haz_Ar.LEN_UNIT`.
    """

    CENTIMETERS = "Centimeters", "Code `CM`."
    FEET = "Feet", "Code `FT`."
    INCHES = "Inches", "Code `IN`."
    KILOMETERS = "Kilometers", "Code `KM`."
    METERS = "Meters", "Code `M`."
    MILES = "Miles", "Code `MI`."
    MILLIMETERS = "Millimeters", "Code `MM`."
    U_S_SURVEY_FEET = "U.S. Survey Feet", "Code `USFT`."
    NP = "NP", "Code `NP`."


class StudyTyp(str, DocumentedEnum):
    """Values of `D_Study_Typ` that apply to the FIRM Database, each as the data stores
    it. Used by `S_Fld_Haz_Ar.STUDY_TYP`. The last 7 are legacy values: common in
    the data, not in the reference.
    """

    BLE_AVAILABLE_BUT_UNPUBLISHED = (
        "BLE available but unpublished",
        (
            "Base Level Engineering data are available, but zones and Baseflood "
            "Elevations (BFEs) are not published on FIRM. Code `1030`."
        ),
    )
    SFHA_WITHOUT_BFE = (
        "SFHA without BFE",
        "Such as A zones without BFEs or water surface elevations. Code `1000`.",
    )
    SFHA_WITH_UNPUBLISHED_BFE = (
        "SFHA with unpublished BFE",
        (
            "Such as A zones with BFEs or water surface elevations calculated but "
            "not published in FIS Report. Code `1040`."
        ),
    )
    SFHA_WITH_BFE_PUBLISHED_ONLY_IN_FIS = (
        "SFHA with BFE published only in FIS",
        (
            "Such as A zones with BFEs or water surface elevations published only "
            "in FIS Report. Code `1010`."
        ),
    )
    SFHA_WITH_BFE_NO_FLOODWAY = (
        "SFHA with BFE no floodway",
        (
            "Such as AE or VE zones with regulatory water surface elevations or "
            "depths but no floodway; or shaded-X zones that are associated with "
            "this type of study. Code `1050`."
        ),
    )
    SFHA_WITH_BFE_AND_FLOODWAY = (
        "SFHA with BFE and floodway",
        (
            "Such as AE or VE zones with regulatory water surface elevations and a "
            "regulatory floodway; or shaded-X zones that are associated with this "
            "type of study. Code `1060`."
        ),
    )
    SHADED_ZONE_X_WITH_DEPTHS_LESS_THAN_1 = (
        "Shaded Zone X with depths less than 1’",
        "Such as Zone X with depths less than 1’. Code `1070`.",
    )
    NP = "NP", "NP; unshaded-X zones. Code `NP`."
    SFHAS_WITH_LOW_FLOOD_RISK = (
        "SFHAs WITH LOW FLOOD RISK",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The November 2016 Domain Tables "
            "reference's study type 1000, one of three graded by flood risk (LOW, "
            "MEDIUM, HIGH) that the February 2019 edition replaced with the "
            "SFHA-with-BFE types the 2024 reference still lists. Held by 979,594 of"
            " 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    SFHAS_WITH_HIGH_FLOOD_RISK = (
        "SFHAs WITH HIGH FLOOD RISK",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The November 2016 Domain Tables "
            "reference's study type 1020, one of three graded by flood risk (LOW, "
            "MEDIUM, HIGH) that the February 2019 edition replaced with the "
            "SFHA-with-BFE types the 2024 reference still lists. Held by 557,235 of"
            " 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    SFHAS_WITH_MEDIUM_FLOOD_RISK = (
        "SFHAs WITH MEDIUM FLOOD RISK",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The November 2016 Domain Tables "
            "reference's study type 1010, one of three graded by flood risk (LOW, "
            "MEDIUM, HIGH) that the February 2019 edition replaced with the "
            "SFHA-with-BFE types the 2024 reference still lists. Held by 193,351 of"
            " 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    REDELINEATION = (
        "REDELINEATION",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The November 2016 Domain Tables "
            "reference's study type 1100. The 2019 and 2024 editions list it as a "
            "study method (D_Study_Mth, the same code), not a study type. Held by "
            "72,844 of 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, "
            "counted 2026-10-05."
        ),
    )
    SHADED_ZONE_X_WITH_DEPTHS_LESS_THAN_1_LEGACY = (
        "Shaded Zone X with depths less than 1'",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The reference's code 1070, "
            "`Shaded Zone X with depths less than 1’`, written with an ASCII "
            "apostrophe where the reference prints a typographic one. More rows "
            "hold this form (33,992) than the reference's (10,645). Held by 33,992 "
            "of 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )
    DIGITAL_CONVERSION = (
        "DIGITAL CONVERSION",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The November 2016 Domain Tables "
            "reference's study type 1200. The 2019 and 2024 editions list it as a "
            "study method (D_Study_Mth, the same code), not a study type. Held by "
            "12,946 of 5,810,832 rows of `STUDY_TYP` on NFHL service layer 28, "
            "counted 2026-10-05."
        ),
    )
    SPECIAL_FLOOD_HAZARD_AREA_SFHA_WITHO = (
        "Special Flood Hazard Area (SFHA) witho",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. The February 2019 Domain Tables "
            "reference's study type 1000, `Special Flood Hazard Area (SFHA) without"
            " BFE`, cut off at the field's 38 characters; the 2024 reference writes"
            " code 1000 `SFHA without BFE`. Held by 6,493 of 5,810,832 rows of "
            "`STUDY_TYP` on NFHL service layer 28, counted 2026-10-05."
        ),
    )


class TrueFalse(str, DocumentedEnum):
    """Values of `D_TrueFalse` that apply to the FIRM Database, each as the data stores
    it. Used by `S_Fld_Haz_Ar.SFHA_TF`, `S_Fld_Haz_Ar.DUAL_ZONE`.
    """

    T = "T", "True (Yes). Code `T`."
    F = "F", "False (No). Code `F`."
    U = "U", "Unknown. Code `U`."


class VDatum(str, DocumentedEnum):
    """Values of `D_V_Datum` that apply to the FIRM Database, each as the data stores
    it. Used by `S_Fld_Haz_Ar.V_DATUM`.
    """

    MSL = "MSL", "Mean Sea Level. Code `MSL`."
    NAVD88 = "NAVD88", "North American Vertical Datum 1988. Code `NAVD88`."
    NGVD29 = "NGVD29", "North American Geodetic Vertical Datum 1929. Code `NGVD29`."
    LOCAL_TIDAL_DATUM = "LOCAL TIDAL DATUM", "Local Tidal Datum. Code `TIDAL`."
    MLLW = "MLLW", "Mean Lower Low Water Datum. Code `MLLW`."
    MLW = "MLW", "Mean Low Water Datum. Code `MLW`."
    GUVD04 = "GUVD04", "Guam Vertical Datum of 2004. Code `GUVD04`."
    NMVD03 = "NMVD03", "Northern Marianas Vertical Datum of 2003. Code `NMVD03`."
    PRVD02 = "PRVD02", "Puerto Rico Vertical Datum of 2002. Code `PRVD02`."
    VIVD09 = "VIVD09", "Virgin Islands Vertical Datum of 2009. Code `VIVD09`."
    NP = "NP", "Code `NP`."


class VelocityUnits(str, DocumentedEnum):
    """Values of `D_Velocity_Units` that apply to the FIRM Database, each as the data
    stores it. Used by `S_Fld_Haz_Ar.VEL_UNIT`.
    """

    CENTIMETERS_DAY = "Centimeters / Day", "Code `1000`."
    CENTIMETERS_HOUR = "Centimeters / Hour", "Code `1010`."
    FEET_SECOND = "Feet / Second", "Code `1020`."
    INCHES_DAY = "Inches / Day", "Code `1030`."
    INCHES_HOUR = "Inches / Hour", "Code `1040`."
    METERS_SECOND = "Meters / Second", "Code `1050`."
    MICROMETERS_SECOND = "Micrometers / Second", "Code `1060`."
    MILLIMETERS_DAY = "Millimeters / Day", "Code `1070`."
    MILLIMETERS_HOUR = "Millimeters / Hour", "Code `1080`."
    NP = "NP", "Code `NP`."


class Zone(str, DocumentedEnum):
    """Values of `D_Zone` that apply to the FIRM Database, each as the data stores it.
    Used by `S_Fld_Haz_Ar.FLD_ZONE`, `S_Fld_Haz_Ar.AR_REVERT`.
    """

    A = "A", "Code `A`."
    A99 = "A99", "Code `A99`."
    AE = "AE", "Code `AE`."
    AH = "AH", "Code `AH`."
    AO = "AO", "Code `AO`."
    AR = "AR", "Code `AR`."
    AREA_NOT_INCLUDED = "AREA NOT INCLUDED", "Code `ANI`."
    D = "D", "Code `D`."
    OPEN_WATER = "OPEN WATER", "Code `OW`."
    V = "V", "Code `V`."
    VE = "VE", "Code `VE`."
    X = "X", "Code `X`."


class ZoneSubtype(str, DocumentedEnum):
    """Values of `D_Zone_Subtype` that apply to the FIRM Database, each as the data
    stores it. Used by `S_Fld_Haz_Ar.ZONE_SUBTY`, `S_Fld_Haz_Ar.AR_SUBTRV`. The last
    is a legacy value: common in the data, not in the reference.
    """

    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Code `0500`. Printed in the reference as "
            "`0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN CHANNEL",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. These subtypes are typically symbolized as "
            "shaded Zone X. “1-PCT FUTURE CONDITIONS” is a subtype of Zone X and "
            "are labeled ZONE X FUTURE on the FIRM panel. Code `0520`. Printed in "
            "the reference as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD CONTAINED IN "
            "CHANNEL`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. These subtypes are typically symbolized as "
            "shaded Zone X. “1-PCT FUTURE CONDITIONS” is a subtype of Zone X and "
            "are labeled ZONE X FUTURE on the FIRM panel. Code `0510`. Printed in "
            "the reference as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD CONTAINED IN "
            "STRUCTURE`."
        ),
    )
    V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL = (
        "1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN CHANNEL",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Code `0210`. Printed in the reference as "
            "`1-PCT-ANNUAL-CHANCE FLOOD HAZARD CONTAINED IN CHANNEL`."
        ),
    )
    V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE = (
        "1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Code `0200`. Printed in the reference as "
            "`1-PCT-ANNUAL-CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE`."
        ),
    )
    V_1_PCT_DEPTH_LESS_THAN_1_FOOT = (
        "1 PCT DEPTH LESS THAN 1 FOOT",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Code `0400`. Printed in the reference as "
            "`1-PCT DEPTH LESS THAN 1 FOOT`."
        ),
    )
    V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE = (
        "1 PCT DRAINAGE AREA LESS THAN 1 SQUARE MILE",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Code `0410`. Printed in the reference as "
            "`1-PCT DRAINAGE AREA LESS THAN 1 SQUARE MILE`."
        ),
    )
    V_1_PCT_FUTURE_CONDITIONS = (
        "1 PCT FUTURE CONDITIONS",
        (
            "These subtypes are typically symbolized as shaded Zone X. “1-PCT "
            "FUTURE CONDITIONS” is a subtype of Zone X and are labeled ZONE X "
            "FUTURE on the FIRM panel. Code `0300`. Printed in the reference as "
            "`1-PCT FUTURE CONDITIONS`."
        ),
    )
    V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE = (
        "1 PCT FUTURE CONDITIONS CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. These subtypes are typically symbolized as "
            "shaded Zone X. “1-PCT FUTURE CONDITIONS” is a subtype of Zone X and "
            "are labeled ZONE X FUTURE on the FIRM panel. Code `0310`. Printed in "
            "the reference as `1-PCT FUTURE CONDITIONS CONTAINED IN STRUCTURE`."
        ),
    )
    ADMINISTRATIVE_FLOODWAY = (
        "ADMINISTRATIVE FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1010`."
        ),
    )
    AREA_OF_SPECIAL_CONSIDERATION = (
        "AREA OF SPECIAL CONSIDERATION",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1020`."
        ),
    )
    AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH REDUCED FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE SYSTEM",
        "Formerly “PROTECTED BY LEVEE.” Code `1000`.",
    )
    AREA_OF_MINIMAL_FLOOD_HAZARD = (
        "AREA OF MINIMAL FLOOD HAZARD",
        (
            "“AREA OF MINIMAL FLOOD HAZARD” terminology is used by Title 44 Code of"
            " Federal Regulations Section 64.3 to define an unshaded Zone X. Code "
            "`2000`."
        ),
    )
    COLORADO_RIVER_FLOODWAY = (
        "COLORADO RIVER FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1040`."
        ),
    )
    COMMUNITY_ENCROACHMENT_AREA = (
        "COMMUNITY ENCROACHMENT AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1030`."
        ),
    )
    DENSITY_FRINGE_AREA = (
        "DENSITY FRINGE AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. "
            "“DENSITY FRINGE AREAS” are a floodway type specific to the State of "
            "Washington used in communities where encroachment and storage-volume "
            "reduction are specified in locations of zoned development, as opposed "
            "to the traditional equal conveyance reduction floodway. Code `1050`."
        ),
    )
    FLOODWAY = (
        "FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1100`."
        ),
    )
    FLOODWAY_CONTAINED_IN_STRUCTURE = (
        "FLOODWAY CONTAINED IN STRUCTURE",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Code `1110`."
        ),
    )
    FLOODWAY_CONTAINED_IN_CHANNEL = (
        "FLOODWAY CONTAINED IN CHANNEL",
        (
            "The CONTAINED IN CHANNEL or CONTAINED IN STRUCTURE zone subtypes "
            "should only be used if the flooding associated with these channelized "
            "structures or other structures is large enough to show as an area. "
            "These features should also be drawn as structures in S_GEN_STRUCT and "
            "coded appropriately there. Code `1120`."
        ),
    )
    FLOWAGE_EASEMENT_AREA = (
        "FLOWAGE EASEMENT AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1200`."
        ),
    )
    NARROW_FLOODWAY = (
        "NARROW FLOODWAY",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1230`."
        ),
    )
    RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE = (
        "RIVERINE FLOODWAY SHOWN IN COASTAL ZONE",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. These"
            " subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `1220`."
        ),
    )
    STATE_ENCROACHMENT_AREA = (
        "STATE ENCROACHMENT AREA",
        (
            "Types of FLOODWAY. Other than the generic “FLOODWAY” subtype, these "
            "are areas in which a community enforces more restrictive criteria for "
            "floodplain management than the minimum requirements of the NFIP. Code "
            "`1210`."
        ),
    )
    COASTAL_FLOODPLAIN = (
        "COASTAL FLOODPLAIN",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `0100`."
        ),
    )
    COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN = (
        "COMBINED RIVERINE AND COASTAL FLOODPLAIN",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `0120`."
        ),
    )
    RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE = (
        "RIVERINE FLOODPLAIN IN COASTAL ZONE",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `0110`."
        ),
    )
    RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE = (
        "RIVERINE FLOODWAY IN COMBINED RIVERINE AND COASTAL ZONE",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `1240`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE = (
        "0.2 PCT ANNUAL CHANCE FLOOD HAZARD IN COASTAL ZONE",
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `0530`. Printed in the reference"
            " as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD IN COASTAL ZONE`."
        ),
    )
    V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE = (
        ("0.2 PCT ANNUAL CHANCE FLOOD HAZARD IN COMBINED RIVERINE AND COASTAL ZONE"),
        (
            "These subtypes are only used in coastal areas to specify riverine or "
            "coastal flooding. More information on these zones can be found in the "
            "FIRM Database Guidance document. Code `0540`. Printed in the reference"
            " as `0.2-PCT-ANNUAL-CHANCE FLOOD HAZARD IN COMBINED RIVERINE AND "
            "COASTAL ZONE`."
        ),
    )
    AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE SYSTEM",
        "Code `3000`.",
    )
    AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM = (
        ("AREA WITH REDUCED FLOOD HAZARD DUE TO PROVISIONALLY ACCREDITED LEVEE SYSTEM"),
        "Code `3010`.",
    )
    AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH UNDETERMINED FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE SYSTEM",
        (
            "This subtype is only used in levee impacted areas with a Zone D from "
            "implementing the Analysis and Mapping Procedures for Non-Accredited "
            "Levee Systems. More information on these procedures can be found in "
            "the Levee Guidance document. Code `3020`."
        ),
    )
    AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM = (
        "AREA WITH REDUCED FLOOD HAZARD DUE TO ACCREDITED LEVEE SYSTEM",
        "Code `3030`.",
    )
    AREA_WITH_REDUCED_FLOOD_RISK_DUE_TO_LEVEE = (
        "AREA WITH REDUCED FLOOD RISK DUE TO LEVEE",
        (
            "Legacy: not in the November 2024 Domain Tables Technical Reference; "
            "validates with a LegacyValueWarning. An older wording of a levee "
            "subtype: the 2024 subtypes say FLOOD HAZARD and LEVEE SYSTEM, and the "
            "reference does not say which of them this one became. Held by 24,849 "
            "of 5,810,832 rows of `ZONE_SUBTY` on NFHL service layer 28, counted "
            "2026-10-05."
        ),
    )


# Members the reference does not list; each use raises a warning.
LEGACY_MEMBERS: frozenset[Enum] = frozenset(
    {
        StudyTyp.SFHAS_WITH_LOW_FLOOD_RISK,
        StudyTyp.SFHAS_WITH_HIGH_FLOOD_RISK,
        StudyTyp.SFHAS_WITH_MEDIUM_FLOOD_RISK,
        StudyTyp.REDELINEATION,
        StudyTyp.SHADED_ZONE_X_WITH_DEPTHS_LESS_THAN_1_LEGACY,
        StudyTyp.DIGITAL_CONVERSION,
        StudyTyp.SPECIAL_FLOOD_HAZARD_AREA_SFHA_WITHO,
        ZoneSubtype.AREA_WITH_REDUCED_FLOOD_RISK_DUE_TO_LEVEE,
    }
)
