"""`S_Fld_Haz_Ar`: Flood Hazard Zones.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import float64, int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.annotations import DatumIn, UnitIn
from nfhl.constraints import (
    Absent,
    AllOf,
    NoneOf,
    OneOf,
    Populated,
    drop_null_encodings,
    forbid_if,
    require_any_true,
    require_if,
)
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    LengthUnits,
    StudyTyp,
    TrueFalse,
    VDatum,
    VelocityUnits,
    Zone,
    ZoneSubtype,
)


@forbid_if(["v_datum"], Absent("static_bfe"))
@forbid_if(["len_unit"], AllOf(Absent("static_bfe"), Absent("depth")))
# “This field is only populated if the corresponding area is Zone AR.”
@forbid_if(["ar_revert"], NoneOf("fld_zone", (Zone.AR,)))
# “This field is only populated if the corresponding area is Zone AR.”
@forbid_if(["ar_subtrv"], NoneOf("fld_zone", (Zone.AR,)))
# “This field is populated when Zone equals AR and the reverted zone has a static
# BFE.”
@forbid_if(["bfe_revert"], NoneOf("fld_zone", (Zone.AR,)))
# “This field is populated when Zone equals AR and the reverted zone has a depth
# assigned.”
@forbid_if(["dep_revert"], NoneOf("fld_zone", (Zone.AR,)))
# “Acceptable values for this field are listed in the D_Zone table, but should only
# include one of AE, AO, AH, A, and X domain values.”
@forbid_if(
    ["ar_revert"],
    OneOf(
        "ar_revert",
        (
            Zone.A99,
            Zone.AR,
            Zone.AREA_NOT_INCLUDED,
            Zone.D,
            Zone.OPEN_WATER,
            Zone.V,
            Zone.VE,
        ),
        label="ar_revert is a D_Zone value other than A, AE, AH, AO, X",
    ),
    "A, AE, AH, AO, X",
)
# “Acceptable values for this field are listed in the D_Zone_Subtype_ table and must
# be one of the allowable subtypes for Zones AE, AO, AH, A or X.”
@forbid_if(
    ["ar_subtrv"],
    OneOf(
        "ar_subtrv",
        (
            ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
            ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
            ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
        ),
        label=(
            "ar_subtrv is a D_Zone_Subtype value Table 14 does not list for any of "
            "A, AE, AH, AO, X"
        ),
    ),
    "A, AE, AH, AO, X",
)
@require_if(["vel_unit"], Populated("velocity"))
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf("fld_zone", (Zone.A,)),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for A, "
                "which allows only 1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN "
                "CHANNEL; 1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE; "
                "COASTAL FLOODPLAIN; COMBINED RIVERINE AND COASTAL FLOODPLAIN; RIVERINE"
                " FLOODPLAIN IN COASTAL ZONE; AREA WITH FLOOD HAZARD DUE TO "
                "NON-ACCREDITED LEVEE SYSTEM"
            ),
        ),
    ),
    "A",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf(
            "fld_zone",
            (
                Zone.A99,
                Zone.AR,
            ),
        ),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.COASTAL_FLOODPLAIN,
                ZoneSubtype.COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN,
                ZoneSubtype.RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for A99, "
                "AR, which allows only AREA WITH REDUCED FLOOD HAZARD DUE TO "
                "NON-ACCREDITED LEVEE SYSTEM"
            ),
        ),
    ),
    "A99, AR",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf("fld_zone", (Zone.AE,)),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for AE, "
                "which allows only 1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN "
                "CHANNEL; 1 PCT ANNUAL CHANCE FLOOD HAZARD CONTAINED IN STRUCTURE; "
                "ADMINISTRATIVE FLOODWAY; AREA OF SPECIAL CONSIDERATION; COLORADO RIVER"
                " FLOODWAY; COMMUNITY ENCROACHMENT AREA; DENSITY FRINGE AREA; FLOODWAY;"
                " FLOODWAY CONTAINED IN STRUCTURE; FLOODWAY CONTAINED IN CHANNEL; "
                "FLOWAGE EASEMENT AREA; NARROW FLOODWAY; STATE ENCROACHMENT AREA; "
                "COASTAL FLOODPLAIN; COMBINED RIVERINE AND COASTAL FLOODPLAIN; RIVERINE"
                " FLOODPLAIN IN COASTAL ZONE; RIVERINE FLOODWAY IN COMBINED RIVERINE "
                "AND COASTAL ZONE; AREA WITH FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE "
                "SYSTEM"
            ),
        ),
    ),
    "AE",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf("fld_zone", (Zone.AH,)),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.COASTAL_FLOODPLAIN,
                ZoneSubtype.COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN,
                ZoneSubtype.RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for AH, "
                "which allows only AREA WITH FLOOD HAZARD DUE TO NON-ACCREDITED LEVEE "
                "SYSTEM"
            ),
        ),
    ),
    "AH",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf("fld_zone", (Zone.AO,)),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.COASTAL_FLOODPLAIN,
                ZoneSubtype.COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN,
                ZoneSubtype.RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for AO, "
                "which allows only FLOODWAY; AREA WITH FLOOD HAZARD DUE TO "
                "NON-ACCREDITED LEVEE SYSTEM"
            ),
        ),
    ),
    "AO",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf(
            "fld_zone",
            (
                Zone.AREA_NOT_INCLUDED,
                Zone.OPEN_WATER,
            ),
        ),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.COASTAL_FLOODPLAIN,
                ZoneSubtype.COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN,
                ZoneSubtype.RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for AREA "
                "NOT INCLUDED, OPEN WATER, which allows only none"
            ),
        ),
    ),
    "AREA NOT INCLUDED, OPEN WATER",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf("fld_zone", (Zone.D,)),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.COASTAL_FLOODPLAIN,
                ZoneSubtype.COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN,
                ZoneSubtype.RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for D, "
                "which allows only AREA WITH UNDETERMINED FLOOD HAZARD DUE TO "
                "NON-ACCREDITED LEVEE SYSTEM"
            ),
        ),
    ),
    "D",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf(
            "fld_zone",
            (
                Zone.V,
                Zone.VE,
            ),
        ),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.V_1_PCT_DEPTH_LESS_THAN_1_FOOT,
                ZoneSubtype.V_1_PCT_DRAINAGE_AREA_LESS_THAN_1_SQUARE_MILE,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS,
                ZoneSubtype.V_1_PCT_FUTURE_CONDITIONS_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_OF_MINIMAL_FLOOD_HAZARD,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COASTAL_ZONE,
                ZoneSubtype.V_0_2_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_PROVISIONALLY_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for V, VE,"
                " which allows only RIVERINE FLOODWAY SHOWN IN COASTAL ZONE; COASTAL "
                "FLOODPLAIN; COMBINED RIVERINE AND COASTAL FLOODPLAIN; RIVERINE "
                "FLOODPLAIN IN COASTAL ZONE; RIVERINE FLOODWAY IN COMBINED RIVERINE AND"
                " COASTAL ZONE"
            ),
        ),
    ),
    "V, VE",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@forbid_if(
    ["zone_subty"],
    AllOf(
        OneOf("fld_zone", (Zone.X,)),
        OneOf(
            "zone_subty",
            (
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_CHANNEL,
                ZoneSubtype.V_1_PCT_ANNUAL_CHANCE_FLOOD_HAZARD_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.ADMINISTRATIVE_FLOODWAY,
                ZoneSubtype.AREA_OF_SPECIAL_CONSIDERATION,
                ZoneSubtype.AREA_WITH_REDUCED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.COLORADO_RIVER_FLOODWAY,
                ZoneSubtype.COMMUNITY_ENCROACHMENT_AREA,
                ZoneSubtype.DENSITY_FRINGE_AREA,
                ZoneSubtype.FLOODWAY,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_STRUCTURE,
                ZoneSubtype.FLOODWAY_CONTAINED_IN_CHANNEL,
                ZoneSubtype.FLOWAGE_EASEMENT_AREA,
                ZoneSubtype.NARROW_FLOODWAY,
                ZoneSubtype.RIVERINE_FLOODWAY_SHOWN_IN_COASTAL_ZONE,
                ZoneSubtype.STATE_ENCROACHMENT_AREA,
                ZoneSubtype.COASTAL_FLOODPLAIN,
                ZoneSubtype.COMBINED_RIVERINE_AND_COASTAL_FLOODPLAIN,
                ZoneSubtype.RIVERINE_FLOODPLAIN_IN_COASTAL_ZONE,
                ZoneSubtype.RIVERINE_FLOODWAY_IN_COMBINED_RIVERINE_AND_COASTAL_ZONE,
                ZoneSubtype.AREA_WITH_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
                ZoneSubtype.AREA_WITH_UNDETERMINED_FLOOD_HAZARD_DUE_TO_NON_ACCREDITED_LEVEE_SYSTEM,
            ),
            label=(
                "zone_subty is a D_Zone_Subtype value Table 14 does not list for X, "
                "which allows only 0.2 PCT ANNUAL CHANCE FLOOD HAZARD; 0.2 PCT ANNUAL "
                "CHANCE FLOOD HAZARD CONTAINED IN CHANNEL; 0.2 PCT ANNUAL CHANCE FLOOD "
                "HAZARD CONTAINED IN STRUCTURE; 1 PCT DEPTH LESS THAN 1 FOOT; 1 PCT "
                "DRAINAGE AREA LESS THAN 1 SQUARE MILE; 1 PCT FUTURE CONDITIONS; 1 PCT "
                "FUTURE CONDITIONS CONTAINED IN STRUCTURE; AREA OF MINIMAL FLOOD "
                "HAZARD; 0.2 PCT ANNUAL CHANCE FLOOD HAZARD IN COASTAL ZONE; 0.2 PCT "
                "ANNUAL CHANCE FLOOD HAZARD IN COMBINED RIVERINE AND COASTAL ZONE; AREA"
                " WITH REDUCED FLOOD HAZARD DUE TO PROVISIONALLY ACCREDITED LEVEE "
                "SYSTEM; AREA WITH REDUCED FLOOD HAZARD DUE TO ACCREDITED LEVEE SYSTEM"
            ),
        ),
    ),
    "X",
)
# Table 14: Flood Zone and Zone Subtype Cross-Walk
@require_if(
    ["zone_subty"],
    OneOf(
        "fld_zone",
        (
            Zone.A99,
            Zone.AR,
            Zone.X,
        ),
    ),
    "A99, AR, X",
)
# “This field will be true for any area coded as an A or V flood zone area.”
@require_any_true(
    ["sfha_tf"],
    NoneOf(
        "fld_zone",
        (
            Zone.A,
            Zone.A99,
            Zone.AE,
            Zone.AH,
            Zone.AO,
            Zone.AR,
            Zone.V,
            Zone.VE,
        ),
    ),
    NoneOf(
        "sfha_tf",
        (
            TrueFalse.F,
            TrueFalse.U,
        ),
    ),
    qualifier="A, A99, AE, AH, AO, AR, V, VE",
)
# “It should be false for any X or D flood areas.”
@require_any_true(
    ["sfha_tf"],
    NoneOf(
        "fld_zone",
        (
            Zone.D,
            Zone.X,
        ),
    ),
    NoneOf(
        "sfha_tf",
        (
            TrueFalse.T,
            TrueFalse.U,
        ),
    ),
    qualifier="D, X",
)
class FloodHazardZone(Feature):
    """This table is required for all FIRM Databases. The S_Fld_Haz_Ar table contains
    information about the flood hazards within the Flood Risk Project area. A
    spatial file with location information also corresponds with this data table.
    These zones are used by FEMA to designate the Special Flood Hazard Area (SFHA).
    These data are the regulatory flood zones designated by FEMA. This information
    is needed for the following tables in the FIS Report: Flooding Sources Included
    in this FIS Report and Summary of Hydrologic and Hydraulic Analyses. The spatial
    elements representing the flood zones are polygons. The entire area of the
    jurisdiction(s) mapped by the FIRM should have a corresponding flood zone
    polygon. There is one polygon for each contiguous flood zone designated.
    Published as layer 28 of the NFHL MapServer, which also carries `GFID`,
    `GlobalID`, `OBJECTID`, `SHAPE.STArea()`, `SHAPE.STLength()`; the reference does
    not define them, so they are optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # A multipart zone is one feature: MultiPolygon as well as Polygon.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.POLYGON, GeometryType.MULTI_POLYGON),
        Field(
            description=(
                "Extent of the flood zone: in the reference's words, one polygon for "
                "each contiguous flood zone designated."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is FLD_AR_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    # Required by the reference, and populated in the state and county downloads, but
    # the NFHL map service does not publish it.
    version_id: Omitable[Annotated[str, MaxLen(11)]] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    fld_ar_id: Annotated[str, MaxLen(32)] = Field(
        alias="FLD_AR_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    study_typ: StudyTyp = Field(
        alias="STUDY_TYP",
        description=(
            "Study Type. This describes the type of Flood Risk Project performed "
            "for flood hazard identification. Acceptable values for this field are "
            "listed in the D_Study_Typ table."
        ),
    )

    fld_zone: Zone = Field(
        alias="FLD_ZONE",
        description=(
            "Flood Zone. This is a flood zone designation. These zones are used by "
            "FEMA to designate the SFHAs. Acceptable values for this field are "
            "listed in the D_Zone table."
        ),
    )

    zone_subty: Omitable[ZoneSubtype] = Field(
        alias="ZONE_SUBTY",
        description=(
            "Flood Zone Subtype. This field captures additional information about "
            "the flood zones. For example, Zone X could have “AREA WITH REDUCED "
            "FLOOD HAZARD DUE TO ACCREDITED LEVEE SYSTEM” or “0.2-PCT ANNUAL CHANCE"
            " FLOOD HAZARD” as a subtype. Types of floodways are also stored in "
            "this field. Floodways are designated by FEMA and adopted by "
            "communities to provide an area that will remain free of development to"
            " moderate increases in flood heights due to encroachment on the "
            "floodplain. Normal floodways are specified as ‘FLOODWAY.’ Special "
            "cases will have a more specific term for the designation (such as "
            "COLORADO RIVER) and will appear as a note on the hardcopy FIRM. See "
            "the FIRM Panel Technical Reference for available floodway notes. NOTE:"
            " The symbol ‘%’ is a reserved symbol in most software packages, so the"
            " word ‘percent’ was abbreviated to ‘PCT.’ Acceptable values for this "
            "field are listed in the D_Zone_Subtype table."
        ),
    )

    sfha_tf: TrueFalse = Field(
        alias="SFHA_TF",
        description=(
            "Special Flood Hazard Area. If the area is within a SFHA this field "
            "would be true. This field will be true for any area coded as an A or V"
            " flood zone area. It should be false for any X or D flood areas. "
            "Acceptable values for this field are listed in the D_TrueFalse table."
        ),
    )

    static_bfe: Omitable[Annotated[float64, UnitIn("LEN_UNIT"), DatumIn("V_DATUM")]] = (
        Field(
            alias="STATIC_BFE",
            description=(
                "Static Base Flood Elevation. This field will be populated for areas "
                "that have been determined to have a constant Base Flood Elevation "
                "(BFE) over a flood zone. The BFE value will be shown beneath the zone "
                "label. In this situation the same BFE applies to the entire polygon. "
                "This normally occurs in lakes or coastal zones."
            ),
        )
    )

    v_datum: Omitable[VDatum] = Field(
        alias="V_DATUM",
        description=(
            "Vertical Datum. The vertical datum indicates the reference surface "
            "from which the flood elevations are measured. Normally this would be "
            "North American Vertical Datum of 1988 for new studies. This field is "
            "only populated if the STATIC_BFE field is populated. Acceptable values"
            " for this field are listed in the D_V_Datum table."
        ),
    )

    depth: Omitable[Annotated[float64, UnitIn("LEN_UNIT")]] = Field(
        alias="DEPTH",
        description=(
            "Depth This is the depth for Zone AO areas. This value is shown beneath"
            " the zone label on the FIRM. This field is only populated if a depth "
            "is shown on the FIRM."
        ),
    )

    len_unit: Omitable[LengthUnits] = Field(
        alias="LEN_UNIT",
        description=(
            "Length Units. This unit indicates the measurement system used for the "
            "BFEs and/or depths. Normally this would be feet. This field is only "
            "populated if the STATIC_BFE or DEPTH field is populated. Acceptable "
            "values for this field are listed in the D_Length_Units table."
        ),
    )

    velocity: Omitable[Annotated[float64, UnitIn("VEL_UNIT")]] = Field(
        alias="VELOCITY",
        description=(
            "Velocity. This is the velocity measurement of the flood flow in the "
            "area. Normally this is applicable to alluvial fan areas (certain Zone "
            "AO areas). This value is shown beneath the zone label on the FIRM. "
            "This field is only populated when a velocity is associated with the "
            "flood zone area."
        ),
    )

    vel_unit: Omitable[VelocityUnits] = Field(
        alias="VEL_UNIT",
        description=(
            "Velocity Unit. This is the unit of measurement for the velocity. This "
            "field is populated when the VELOCITY field is populated. Acceptable "
            "values for this field are listed in the D_Velocity_Units table."
        ),
    )

    ar_revert: Omitable[Zone] = Field(
        alias="AR_REVERT",
        description=(
            "Flood Control Restoration Zones – Zone AR Classification. If this area"
            " is Zone AR in FLD_Zone field, this field would hold the zone that "
            "area would revert to if the AR zone were removed. This field is only "
            "populated if the corresponding area is Zone AR. Acceptable values for "
            "this field are listed in the D_Zone table, but should only include one"
            " of AE, AO, AH, A, and X domain values."
        ),
    )

    ar_subtrv: Omitable[ZoneSubtype] = Field(
        alias="AR_SUBTRV",
        description=(
            "Flood Control Restoration Zones – Zone AR Classification Zone Subtype."
            " If this area is Zone AR in FLD_Zone field, this field would hold the "
            "zone subtype that area would revert to if the AR zone were removed. "
            "This field is only populated if the corresponding area is Zone AR. "
            "NOTE: The symbol ‘%’ is a reserved symbol in most software packages, "
            "so the word ‘percent’ was abbreviated to ‘PCT.’ Acceptable values for "
            "this field are listed in the D_Zone_Subtype_ table and must be one of "
            "the allowable subtypes for Zones AE, AO, AH, A or X."
        ),
    )

    bfe_revert: Omitable[float64] = Field(
        alias="BFE_REVERT",
        description=(
            "Flood Control Restoration Zones – BFE Revert. If zone is Zone AR in "
            "FLD_Zone field, this field would hold the static base flood elevation "
            "for the reverted zone. This field is populated when Zone equals AR and"
            " the reverted zone has a static BFE."
        ),
    )

    dep_revert: Omitable[float64] = Field(
        alias="DEP_REVERT",
        description=(
            "Flood Control Restoration Zones – Depth Revert. If zone is Zone AR in "
            "FLD_Zone field, this field would hold the flood depth for the reverted"
            " zone. This field is populated when Zone equals AR and the reverted "
            "zone has a depth assigned."
        ),
    )

    dual_zone: Omitable[TrueFalse] = Field(
        alias="DUAL_ZONE",
        description=(
            "Flood Control Restoration Zones – Dual Zone Classification. If the "
            "flood hazard areas shown on the effective FIRM shall be designated as "
            "“dual” SFHAs (i.e., Zone AR/AE, Zone AR/AH, Zone AR/AO, Zone AR/A), "
            "this field will be coded as true. It should be false for any for AR "
            "Zones that revert to Shaded X. Acceptable values for this field are "
            "listed in the D_TrueFalse table."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_starea: Omitable[float64] = Field(
        alias="SHAPE.STArea()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_stlength: Omitable[float64] = Field(
        alias="SHAPE.STLength()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
