"""`S_Levee`: Levees.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import float64, int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.annotations import UnitIn
from nfhl.constraints import (
    AllOf,
    NoneOf,
    OneOf,
    drop_null_encodings,
    forbid_if,
    require_if,
)
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    LengthUnits,
    LeveeAnalysisType,
    LeveeStatus,
    LeveeTyp,
    TrueFalse,
    USACEDistrict,
)


# “This should only be populated if LEVEE_STAT is Non-Accredited.”
# “the FEMA Project Officer may allow the Mapping Partner to substitute a value that
# indicates that the affected field was intentionally not populated.”
@forbid_if(
    ["lev_an_typ"],
    AllOf(
        NoneOf("levee_stat", (LeveeStatus.NON_ACCREDITED,)),
        NoneOf("lev_an_typ", (LeveeAnalysisType.NP,)),
    ),
)
# “Field is required when the structure is owned or maintained by the USACE, with a
# value of “T” in the USACE_LEV field.”
@require_if(["district"], OneOf("usace_lev", (TrueFalse.T,)))
class Levee(Feature):
    """The S_Levee table contains information about levees shown on the FIRMs that are
    accredited and known to be protecting against the 1% annual-chance flood, as
    well as levees that are provisionally accredited, and non-accredited. The
    purpose of this table is to document the accreditation status of levees, as well
    as associated information necessary to be shown on the FIRM and for the
    population of FIS Report text related to levee structures. The spatial entities
    representing levees are lines, drawn at the centerline of levees, floodwalls and
    levee closure structures. Published as layer 23 of the NFHL MapServer, which
    also carries `GFID`, `GlobalID`, `OBJECTID`, `SHAPE.STLength()`; the reference
    does not define them, so they are optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("", -9999 and 9/9/9999) mean not
    # populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # Table 4 holds S_Levee to “Must Be Single Part”, so a LineString, though the
    # service's polyline type admits several parts.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.LINE_STRING),
        Field(
            description=(
                "The levee: in the reference's words, a line drawn at the centerline of"
                " a levee, floodwall or levee closure structure shown on the FIRM, with"
                " its accreditation status."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is LEVEE_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single-jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    levee_id: Annotated[str, MaxLen(32)] = Field(
        alias="LEVEE_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    # Length 32 on the service; the reference says 25.
    fc_sys_id: Annotated[str, MaxLen(32)] = Field(
        alias="FC_SYS_ID",
        description=(
            "National Levee Database (NLD) System ID (FC_SYSTEM). The unique "
            "identifier, assigned in the NLD, for each levee system with which a "
            "levee segment is associated. Used to link levee systems in the NFHL "
            "with the NLD, where more detailed information about each levee system "
            "can be found."
        ),
    )

    levee_nm: Omitable[Annotated[str, MaxLen(100)]] = Field(
        alias="LEVEE_NM",
        description=(
            "Any commonly used name for the levee. Required in the reference, with "
            'the footnote "Field is applicable for BLE database."'
        ),
    )

    levee_typ: Omitable[LeveeTyp] = Field(
        alias="LEVEE_TYP",
        description=(
            "Describes the type of protecting structure. Valid values can be found "
            "in the D_Levee_Typ domain table. Required in the reference, with the "
            'footnote "Field is applicable for BLE database."'
        ),
    )

    wtr_nm: Omitable[Annotated[str, MaxLen(100)]] = Field(
        alias="WTR_NM",
        description=(
            "Surface Water Feature Name. Name of the water body that the levee "
            "structure or segment is providing protection from. Required in the "
            'reference, with the footnote "Field is applicable for BLE database."'
        ),
    )

    bank_loc: Omitable[Annotated[str, MaxLen(100)]] = Field(
        alias="BANK_LOC",
        description=(
            "Bank Location of Levee. A field to describe the location of the levee "
            "centerline in relation to the water body. For example, “Left Bank,” "
            '“Right Bank.” Required in the reference, with the footnote "Field is '
            'applicable for BLE database."'
        ),
    )

    usace_lev: Omitable[TrueFalse] = Field(
        alias="USACE_LEV",
        description=(
            "Determines if this is a U.S. Army Corps of Engineers (USACE) Levee. "
            "Valid values can be found in the D_TrueFalse domain table. Required in"
            ' the reference, with the footnote "Field is applicable for BLE '
            'database."'
        ),
    )

    district: Omitable[USACEDistrict] = Field(
        alias="DISTRICT",
        description=(
            "USACE District Code. This is the code for the USACE district "
            "responsible for the segment. Field is required when the structure is "
            "owned or maintained by the USACE, with a value of “T” in the USACE_LEV"
            " field. Valid values can be found in the D_USACE_District domain "
            "table."
        ),
    )

    pl84_99tf: Omitable[TrueFalse] = Field(
        alias="PL84_99TF",
        description=(
            "Status of levee. This field indicates if the levee is covered under "
            "PL84-99, which is the USACE authority to provide emergency assistance "
            "and repair damaged levees. Valid values can be found in the "
            "D_TrueFalse domain table. Required in the reference, with the footnote"
            ' "Field is applicable for BLE database."'
        ),
    )

    const_date: Omitable[int64] = Field(
        alias="CONST_DATE",
        description="Construction Date. Date on which construction was completed.",
    )

    dgn_freq: Omitable[Annotated[str, MaxLen(50)]] = Field(
        alias="DGN_FREQ",
        description=(
            "Design Frequency. Enter the design frequency of the levee, if known. "
            "For accredited levees, a valid entry in this field is required."
        ),
    )

    freeboard: Omitable[Annotated[float64, UnitIn("LEN_UNIT")]] = Field(
        alias="FREEBOARD",
        description=(
            "Freeboard Value. For accredited levees, enter the smallest amount of "
            "freeboard above the 1% annual-chance flood along the entire levee, "
            "floodwall, closure structure or embankments."
        ),
    )

    levee_stat: Omitable[LeveeStatus] = Field(
        alias="LEVEE_STAT",
        description=(
            "Levee Status. This field stores the accreditation status of the levee."
            " Acceptable values for this field are listed in the D_Levee_Status "
            'table. Required in the reference, with the footnote "Field is '
            'applicable for BLE database."'
        ),
    )

    pal_date: Omitable[int64] = Field(
        alias="PAL_DATE",
        description=(
            "Provisionally Accredited Levee Date. This field stores the end date of"
            " the Provisionally Accredited Levee (PAL) period for the levee "
            "associated with the flood zone. This field is populated for those "
            "structure features that have a PAL designation."
        ),
    )

    lev_an_typ: Omitable[LeveeAnalysisType] = Field(
        alias="LEV_AN_TYP",
        description=(
            "Levee Analysis Type for Non-Accredited Levees. This should only be "
            "populated if LEVEE_STAT is Non-Accredited. Acceptable values for this "
            "field are listed in the D_Levee_Analysis_Type table."
        ),
    )

    fc_seg_id: Annotated[str, MaxLen(25)] = Field(
        alias="FC_SEG_ID",
        description=(
            "National Levee Database (NLD) Segment ID (FC_SEGMENT). If the levee, "
            "floodwall or closure structure is included in the NLD, this is the "
            "segment identification number assigned in the NLD. This field is "
            "populated for all flood control features, included in the NLD, "
            "regardless of their status."
        ),
    )

    owner: Omitable[Annotated[str, MaxLen(100)]] = Field(
        alias="OWNER",
        description=(
            "Levee Owner. Name of the entity that owns the levee. Required in the "
            'reference, with the footnote "Field is applicable for BLE database."'
        ),
    )

    len_unit: Omitable[LengthUnits] = Field(
        alias="LEN_UNIT",
        description=(
            "This unit indicates the measurement system used for the freeboard "
            "elevations. Normally this would be feet. Acceptable values for this "
            "field are listed in the D_Length_Units table."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_stlength: Omitable[float64] = Field(
        alias="SHAPE.STLength()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
