"""`S_Profil_Basln`: Profile Baselines.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import float64, int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.annotations import UnitIn
from nfhl.constraints import Absent, drop_null_encodings, forbid_if
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    LengthUnits,
    ProfBaslnTyp,
    StudyTyp,
    TrueFalse,
)


@forbid_if(["fld_prob2"], Absent("fld_prob1"))
@forbid_if(["fld_prob3"], Absent("fld_prob2"))
@forbid_if(["spec_cons2"], Absent("spec_cons1"))
class ProfileBaseline(Feature):
    """Location and attributes for profile baseline and stream centerline features for
    the Flood Risk Project area. Published as layer 17 of the NFHL MapServer, which
    also carries `GFID`, `GlobalID`, `OBJECTID`, `SHAPE.STLength()`; the reference
    does not define them, so they are optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # Table 4 holds S_Profil_Basln to “Must Be Single Part”, so a LineString, though the
    # service's polyline type admits several parts.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.LINE_STRING),
        Field(
            description=(
                "The profile baseline: in the reference's words, the location of a "
                "profile baseline or stream centerline feature for the Flood Risk "
                "Project area."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is BASELN_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single-jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    baseln_id: Annotated[str, MaxLen(32)] = Field(
        alias="BASELN_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    wtr_nm: Annotated[str, MaxLen(100)] = Field(
        alias="WTR_NM",
        description=(
            "Surface Water Feature Name. This is the formal name of the surface "
            "water feature as it will appear on the hardcopy FIRM."
        ),
    )

    segmt_name: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="SEGMT_NAME",
        description=(
            "Segment Name. This is an optional identification string for each link."
            " If used, this value must be unique for a stream."
        ),
    )

    water_typ: Omitable[ProfBaslnTyp] = Field(
        alias="WATER_TYP",
        description=(
            "Surface Water Feature Type. The type value describes the kind of "
            "watercourse represented. In the FIRM Database, this layer contains "
            "profile baselines and/or streams that are coincident with profile "
            "baselines. Acceptable values for this field are listed in the "
            "D_Prof_Basln_Typ table. Required in the reference, with the footnote "
            '"Field is applicable for BLE database."'
        ),
    )

    study_typ: Omitable[StudyTyp] = Field(
        alias="STUDY_TYP",
        description=(
            "Study Type. This describes the type of Flood Risk Project performed "
            "for flood hazard identification. Acceptable values for this field are "
            "listed in the D_Study_Typ table. Required in the reference, with the "
            'footnote "Field is applicable for BLE database."'
        ),
    )

    shown_firm: Omitable[TrueFalse] = Field(
        alias="SHOWN_FIRM",
        description=(
            "Profile Baseline Shown on FIRM. This field is true only if the profile"
            " baseline is shown on the FIRM. Because various FIS tables require a "
            "profile baseline for all studied reaches regardless of zone "
            "designation, this field must be populated to determine which profile "
            "baselines are to be shown on the FIRM panels. Acceptable values for "
            "this field are listed in the D_TrueFalse table. Required in the "
            'reference, with the footnote "Field is applicable for BLE database."'
        ),
    )

    # The NFHL map service does not publish it.
    shown_indx: Omitable[TrueFalse] = Field(
        alias="SHOWN_INDX",
        description=(
            "Profile Baseline Shown on Index. This field is true only if the "
            "profile baseline is shown on the Index rather than use of S_Wtr_Ln."
        ),
    )

    r_st_desc: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="R_ST_DESC",
        description=(
            "Reach Name Start Description. This describes the location of the start"
            " of the Flood Risk Project reach. Required in the reference, with the "
            'footnote "Field is applicable for BLE database."'
        ),
    )

    r_end_desc: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="R_END_DESC",
        description=(
            "Reach Name End Description. This describes the location of the end of "
            "the Flood Risk Project reach. Required in the reference, with the "
            'footnote "Field is applicable for BLE database."'
        ),
    )

    v_datm_off: Omitable[Annotated[Annotated[str, MaxLen(6)], UnitIn("DATUM_UNIT")]] = (
        Field(
            alias="V_DATM_OFF",
            description=(
                "Vertical Datum Offset (Conversion Factor). Populated if a single "
                "vertical datum offset cannot be used across the Flood Risk Project and"
                " offset values must be calculated stream by stream."
            ),
        )
    )

    datum_unit: Omitable[LengthUnits] = Field(
        alias="DATUM_UNIT",
        description=(
            "Length Datum Offset (Conversion Factor) Units. This is the unit of "
            "measure for the vertical datum offset (conversion factor) distance "
            "height. Acceptable values for the field are listed in the "
            "D_Length_Units table."
        ),
    )

    fld_prob1: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="FLD_PROB1",
        description="Description of Flooding Problems by flooding source.",
    )

    fld_prob2: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="FLD_PROB2",
        description=(
            "Description of Flooding Problems by flooding source, continued. Used "
            "when FLD_PRB1 field does not have enough characters to hold the "
            "flooding problem description."
        ),
    )

    fld_prob3: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="FLD_PROB3",
        description=(
            "Description of Flooding Problems by flooding source, continued. Used "
            "when FLD_PRB1 and FLD_PRB2 fields do not have enough characters to "
            "hold the flooding problem description."
        ),
    )

    spec_cons1: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="SPEC_CONS1",
        description=(
            "Special Considerations field for describing the modeling methodology used."
        ),
    )

    spec_cons2: Omitable[Annotated[str, MaxLen(254)]] = Field(
        alias="SPEC_CONS2",
        description=(
            "Second Special Considerations field for describing the modeling "
            "methodology used. Use this field when the description cannot be "
            "contained within the SPEC_CONS1 field."
        ),
    )

    # Length 32 on the service; the reference says 25.
    start_id: Omitable[Annotated[str, MaxLen(32)]] = Field(
        alias="START_ID",
        description=(
            "Station Start Identification. This is the foreign key to the "
            "S_Stn_Start layer. This field is the link that is used to reference "
            "station start descriptions in the FDTs and profiles and which links "
            "the S_Profil_Basln table, L_XS_Elev table via the S_XS table and river"
            " marks in the S_Riv_Mrk table to the appropriate stationing starting "
            'point. Required in the reference, with the footnote "Field is '
            'applicable for BLE database."'
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_stlength: Omitable[float64] = Field(
        alias="SHAPE.STLength()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
