"""`S_Riv_Mrk`: River Mile Markers.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.constraints import drop_null_encodings
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
)


class RiverMark(Feature):
    """The S_Riv_Mrk table contains information about the river marks shown on the FIRM
    if applicable. A spatial file with location information also corresponds with
    this data table. The spatial entities representing the river marks are points.
    The points are generally located along the centerline of the river at regular
    intervals or as indicated by the data source. Published as layer 7 of the NFHL
    MapServer, which also carries `GFID`, `GlobalID`, `OBJECTID`; the reference does
    not define them, so they are optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # “The spatial entities representing the river marks are points”, so a Point, as the
    # service's point type is: Esri publishes several points as esriGeometryMultipoint.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.POINT),
        Field(
            description=(
                "The river mark: in the reference's words, a point generally located "
                "along the centerline of the river at regular intervals or as indicated"
                " by the data source."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is RIV_MRK_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single-jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    riv_mrk_id: Annotated[str, MaxLen(32)] = Field(
        alias="RIV_MRK_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    # Length 32 on the service; the reference says 25.
    start_id: Annotated[str, MaxLen(32)] = Field(
        alias="START_ID",
        description=(
            "Station Start Identification. This is the foreign key to the "
            "S_Stn_Start layer. A code that provides a link to a point in the "
            "S_Stn_Start table at which the river mark distances start."
        ),
    )

    riv_mrk_no: Annotated[str, MaxLen(6)] = Field(
        alias="RIV_MRK_NO",
        description=(
            "River Mark Number. This attribute usually represents the distance from"
            " a known point (identified by START_ID), such as the confluence with "
            "another river, to the current river mark. This is the value shown next"
            " to the river mark on the FIRM."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
