"""`S_Stn_Start`: Station Start Points.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.constraints import drop_null_encodings
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    LocAccuracy,
)


class StationStart(Feature):
    """The S_Stn_Start table contains information about station starting locations.
    These locations indicate the reference point that was used as the origin for
    distance measurements along streams and rivers. This table is referenced by both
    the L_XS_Elev table, which contains stream station information for cross
    sections and the S_Riv_Mrk table, which contains river distance marker points.
    Published as layer 13 of the NFHL MapServer, which also carries `GFID`,
    `GlobalID`, `OBJECTID`; the reference does not define them, so they are optional
    and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # “These locations indicate the reference point that was used as the origin”, so a
    # Point, as the service's point type is: Esri publishes several points as
    # esriGeometryMultipoint.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.POINT),
        Field(
            description=(
                "The station starting location: in the reference's words, the reference"
                " point that was used as the origin for distance measurements along "
                "streams and rivers."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is START_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Flood Risk Project Identifier. For a single-jurisdiction Flood Risk "
            "Project, the value is composed of the two-digit State FIPS code and "
            "the four-digit FEMA CID code (e.g., 480001). For a countywide Flood "
            "Risk Project, the value is composed of the two-digit State FIPS code, "
            "the three-digit county FIPS code and the letter “C” (e.g., 48107C). "
            "Within each FIRM Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    start_id: Annotated[str, MaxLen(32)] = Field(
        alias="START_ID",
        description=(
            "Primary key for table lookup. Assigned by table creator. This field is"
            " the link that is used to reference station start descriptions in the "
            "FDTs and profiles and which links the S_Profil_Basln table, L_XS_Elev "
            "table via the S_XS table, and river marks in the S_Riv_Mrk table to "
            "the appropriate stationing starting point."
        ),
    )

    start_desc: Annotated[str, MaxLen(254)] = Field(
        alias="START_DESC",
        description=(
            "Start Description. The description of the location of the station "
            "starting point. This should include the measurement units. For "
            "example, “Distances are measured in feet upstream from the confluence "
            "with the Main Channel of the Big River.”"
        ),
    )

    loc_acc: LocAccuracy = Field(
        alias="LOC_ACC",
        description=(
            "Start Station Locational Accuracy. The spatial placement accuracy "
            "level of the Station Start point. For all new models with profile "
            "baselines, the exact location of the profile baseline station start "
            "should be placed and the locational accuracy be categorized as “HIGH.”"
            " For old models where the profile baseline and station start are "
            "documented on work maps, the locational accuracy is “MEDIUM.” For "
            "areas that only have a text description, the point shall be placed as "
            "best possible, and the locational accuracy will be attributed as "
            "“LOW.” The acceptable values for this field can be found in the "
            "D_Loc_Accuracy table."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
