"""`S_Wtr_Ln`: Water Lines.

GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not
edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,
then regenerate.
"""

from __future__ import annotations

from typing import Annotated

from annotated_types import MaxLen
from overture.schema.system.feature import Feature
from overture.schema.system.geometric import (
    Geometry,
    GeometryType,
    GeometryTypeConstraint,
)
from overture.schema.system.numeric import float64, int64
from overture.schema.system.optionality import Omitable
from pydantic import ConfigDict, Field, model_validator

from nfhl.constraints import drop_null_encodings
from nfhl.legacy import warn_on_legacy_values
from nfhl.models.enums import (
    LEGACY_MEMBERS,
    REFERENCE_EDITION,
    TrueFalse,
)


class WaterLine(Feature):
    """The S_Wtr_Ln table contains information about surface water linear features. A
    spatial file with location information also corresponds with this data table.
    The spatial elements representing surface water line features are lines. Surface
    water features may appear in either the S_Wtr_Ar table or the S_Wtr_Ln table or
    both. However, features that appear in both must match exactly. The hydrologic
    structure of the modeled stream network will be represented by the
    S_Profil_Basln layer. This information is used in the Transect Locator Map and
    the FIRM Panel Index in the FIS Report, as well as the FIRM panels. Published as
    layer 20 of the NFHL MapServer, which also carries `GFID`, `GlobalID`,
    `OBJECTID`, `SHAPE.STLength()`; the reference does not define them, so they are
    optional and validated only by type.
    """

    model_config = ConfigDict(
        # Properties neither source defines stay extras.
        extra="allow",
        populate_by_name=True,
        serialize_by_alias=True,
    )

    # The reference's null encodings ("" and -9999) mean not populated.
    _drop_null_encodings = model_validator(mode="before")(
        staticmethod(drop_null_encodings)
    )

    # A value the reference does not list but the data commonly holds
    # validates, with a LegacyValueWarning.
    _warn_on_legacy_values = model_validator(mode="after")(
        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)
    )

    # Table 4 holds S_Wtr_Ln to “Must Be Single Part”, so a LineString, though the
    # service's polyline type admits several parts.
    geometry: Annotated[
        Geometry,
        GeometryTypeConstraint(GeometryType.LINE_STRING),
        Field(
            description=(
                "The water line: in the reference's words, a surface water linear "
                "feature (a stream, as a line) that appears on the FIRM."
            )
        ),
    ]

    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON
    # output writes the service's integer OBJECTID here.
    id: Omitable[int64] = Field(  # type: ignore[assignment]
        description=(
            "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
            "feature id. It numbers rows in one copy of the service and identifies "
            "nothing beyond it; the reference's key is WTR_LN_ID, assigned within "
            "one FIRM Database (one DFIRM_ID)."
        ),
    )

    dfirm_id: Annotated[str, MaxLen(6)] = Field(
        alias="DFIRM_ID",
        description=(
            "Study Identifier. For a single-jurisdiction Flood Risk Project, the "
            "value is composed of the two-digit State FIPS code and the four-digit "
            "FEMA CID code (e.g., 480001). For a countywide Flood Risk Project, the"
            " value is composed of the two-digit State FIPS code, the three-digit "
            "county FIPS code and the letter “C” (e.g., 48107C). Within each FIRM "
            "Database, the DFIRM_ID value will be identical."
        ),
    )

    version_id: Annotated[str, MaxLen(11)] = Field(
        alias="VERSION_ID",
        description=(
            "Version Identifier. Identifies the product version and relates the "
            "feature to standards according to how it was created."
        ),
    )

    # Length 32 on the service; the reference says 25.
    wtr_ln_id: Annotated[str, MaxLen(32)] = Field(
        alias="WTR_LN_ID",
        description="Primary key for table lookup. Assigned by table creator.",
    )

    wtr_nm: Annotated[str, MaxLen(100)] = Field(
        alias="WTR_NM",
        description=(
            "Surface Water Feature Name. This is the formal name of the surface "
            "water feature, as it will appear on the hardcopy FIRM."
        ),
    )

    shown_firm: Omitable[TrueFalse] = Field(
        alias="SHOWN_FIRM",
        description=(
            "Shown on FIRM. If the water feature is shown on the FIRM, this field "
            "would be True. Water features that obscure a profile baseline feature "
            "for the same reach should be attributed as False. Used for "
            "cartographic representation. Acceptable values for this field are "
            "listed in D_TrueFalse."
        ),
    )

    shown_indx: Omitable[TrueFalse] = Field(
        alias="SHOWN_INDX",
        description=(
            "Shown on Index Map. If the water feature is shown on the Index Map, "
            "this field would be True. Due to the scale of the Index Map format, "
            "lower order and overly detailed water features would be attributed as "
            "False to avoid clutter on the map. Used for cartographic "
            "representation. Acceptable values for this field are listed in "
            "D_TrueFalse."
        ),
    )

    # Length 21 on the service; the reference says 11.
    source_cit: Annotated[str, MaxLen(21)] = Field(
        alias="SOURCE_CIT",
        description=(
            "Source Citation. Abbreviation used in the metadata file when "
            "describing the source information for the feature. The abbreviation "
            "must match a value in L_Source_Cit."
        ),
    )

    # Housekeeping columns only the service has.
    gfid: Omitable[Annotated[str, MaxLen(36)]] = Field(
        alias="GFID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    globalid: Omitable[Annotated[str, MaxLen(38)]] = Field(
        alias="GlobalID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    objectid: Omitable[int64] = Field(
        alias="OBJECTID",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )

    shape_stlength: Omitable[float64] = Field(
        alias="SHAPE.STLength()",
        description=(
            "Published by the NFHL map service as housekeeping for its own copy of "
            "the data; the FIRM Database reference does not define it."
        ),
    )
