"""The generator is a function of the snapshot."""

from __future__ import annotations

from pathlib import Path

from nfhl.codegen import MODELS_DIR, generate


def test_regenerating_from_the_snapshot_changes_nothing(tmp_path: Path) -> None:
    out = tmp_path / "models"
    generate(out)
    fresh = {p.name: p.read_text() for p in out.glob("*.py")}
    committed = {p.name: p.read_text() for p in MODELS_DIR.glob("*.py")}
    assert fresh.keys() == committed.keys()
    for name in fresh:
        assert fresh[name] == committed[name], f"{name} is stale; run generate-models"


def test_the_committed_models_are_marked_generated() -> None:
    for path in MODELS_DIR.glob("*.py"):
        assert "GENERATED by `scripts/generate-models`" in path.read_text(), path
