"""Generate the models in `nfhl.models` from the pinned spec/ snapshot.

Unlike gatis, whose bootstrap writes once and then hands the models over, these
are a build artifact: every file under `src/nfhl/models/` is rewritten on each
run, and `tests/test_codegen.py` regenerates into a temporary directory and
asserts there is no diff. Anything a model needs to say that the snapshot does
not is said in `spec/repairs.json` or `spec/relationships.json`, each entry
quoting its licence from the reference, so it survives regeneration and stays
traceable.

What comes from where:

* field set, order, meaning, requirement and domain -- the FIRM Database
  Technical Reference (`ReferenceTable`);
* Esri type and text length -- the NFHL service, which is what is published;
  the reference's own type is cross-checked and a disagreement raises;
* allowed values -- the Domain Tables Technical Reference, after repairs;
* unit, datum and populated-only-if relationships, the values a field is
  limited to, and values one field takes from another --
  `spec/relationships.json`;
* which subtypes each flood zone allows -- Table 14 of the FIRM Database
  reference, the zone/subtype cross-walk;
* what a feature's geometry may be -- each table's introduction (`GEOMETRIES`),
  checked against the service's geometry type.
"""

from __future__ import annotations

import json
import keyword
import re
import shutil
import subprocess
import textwrap
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from nfhl.spec_source import (
    CROSSWALK_LICENCE,
    LAYERS,
    Allowed,
    Domain,
    DomainValue,
    Layer,
    LegacyValue,
    PairRule,
    ReferenceField,
    ReferenceTable,
    ServiceField,
    SpecReader,
)

MODELS_DIR = Path(__file__).resolve().parent / "models"

HEADER = (
    "GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not\n"
    "edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,\n"
    "then regenerate."
)

# The reference's type names against the service's. A field whose two sources
# disagree is a defect to look at, not one to resolve by picking a side.
ESRI_TYPES = {
    "esriFieldTypeString": "Text",
    "esriFieldTypeDouble": "Double",
    "esriFieldTypeSingle": "Float",
    "esriFieldTypeInteger": "Long Integer",
    "esriFieldTypeSmallInteger": "Short Integer",
    "esriFieldTypeDate": "Date",
}
# A footnoted requirement letter, as the field description words it.
FOOTNOTED_REQUIREMENTS = {"R": "Required", "A": "Required if applicable"}
PYTHON_TYPES = {"Text": "str", "Double": "float64", "Short Integer": "int16"}

# Fields the service publishes and the reference does not define, by their Esri type.
SERVICE_ONLY_TYPES = {
    "esriFieldTypeOID": "int64",
    "esriFieldTypeGlobalID": "str",
    "esriFieldTypeString": "str",
    "esriFieldTypeDouble": "float64",
}

SERVICE_ONLY_DESCRIPTION = (
    "Published by the NFHL map service as housekeeping for its own copy of the "
    "data; the FIRM Database reference does not define it."
)

# What a generated model may import from `nfhl.constraints`, besides
# `drop_null_encodings`; each model imports the ones its rules use.
CONSTRAINT_NAMES = (
    "Absent",
    "AllOf",
    "NoneOf",
    "OneOf",
    "Populated",
    "forbid_if",
    "require_any_true",
    "require_if",
)

WIDTH = 70  # string chunk width before ruff format lays the code out


@dataclass(frozen=True, slots=True)
class ModelFile:
    path: str
    source: str


def literal(text: str) -> str:
    """A Python string literal for `text`, split into chunks ruff will wrap."""
    chunks = textwrap.wrap(
        text,
        WIDTH,
        break_long_words=False,
        break_on_hyphens=False,
        drop_whitespace=False,
    ) or [""]
    parts = [json.dumps(c, ensure_ascii=False) for c in chunks]
    return parts[0] if len(parts) == 1 else "(" + " ".join(parts) + ")"


def docstring(text: str, indent: str) -> str:
    if '"""' in text or "\\" in text:
        raise ValueError(f"cannot render as a docstring: {text!r}")
    body = textwrap.fill(text, 84 - len(indent), break_on_hyphens=False)
    lines = body.splitlines()
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""'
    joined = "\n".join(f"{indent}{line}" if line else "" for line in lines)
    return f'{indent}"""{joined.lstrip()}\n{indent}"""'


def member_name(value: str) -> str:
    name = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not name or name[0].isdigit():
        name = f"V_{name}"
    return f"{name}_" if keyword.iskeyword(name.lower()) else name


def sentence(text: str) -> str:
    """`text` ending in exactly one full stop, inside a closing quote or not."""
    return text if re.search(r"\.[”\"’]?$", text) else f"{text}."


def member_doc(value: DomainValue) -> str:
    """What a stored value means, in the reference's own words, then its code."""
    parts = [
        sentence(text)
        for text in (value.meaning, value.when_used, *value.footnotes)
        if text
    ]
    parts.append(f"Code `{value.code}`.")
    if value.published != value.value:
        parts.append(f"Printed in the reference as `{value.published}`.")
    return " ".join(parts)


def legacy_doc(entries: list[LegacyValue], reader: SpecReader) -> str:
    """Marks the member legacy, says how common it is and where that was counted.

    `entries` are one value's entries in `spec/legacy.json`, one per layer whose
    threshold it clears: an enum serves every layer whose field uses its
    domain, so the member is legacy on all of them.
    """
    notes = list(dict.fromkeys(sentence(e.note) for e in entries))
    held = []
    for e in entries:
        total = reader.observed(next(lyr for lyr in LAYERS if lyr.layer_id == e.layer))
        day = reader.legacy_counted_at(e.layer)[:10]
        held.append(
            f"{e.count:,} of {total['total']:,} rows of `{e.field}` on NFHL "
            f"service layer {e.layer}, counted {day}"
        )
    return (
        f"Legacy: not in the {reader.edition} Domain Tables Technical Reference; "
        f"validates with a LegacyValueWarning. {' '.join(notes)} "
        f"Held by {'; and by '.join(held)}."
    )


@dataclass(frozen=True, slots=True)
class RenderedEnum:
    source: str
    legacy_members: list[str]  # `Class.MEMBER`, for the module's LEGACY_MEMBERS


def render_enum(domain: Domain, used_by: list[str], reader: SpecReader) -> RenderedEnum:
    legacy: dict[str, list[LegacyValue]] = {}
    for entry in reader.legacy_values(domain.name):
        legacy.setdefault(entry.value, []).append(entry)
    names = [member_name(v.value) for v in domain.values]
    legacy_names = []
    for legacy_value in legacy:
        name = member_name(legacy_value)
        # `... less than 1'` differs from the reference's `1’` only in punctuation.
        legacy_names.append(f"{name}_LEGACY" if name in names else name)
    every = names + legacy_names
    if len(set(every)) != len(every):
        raise ValueError(f"{domain.name}: member names collide: {every}")
    fields = ", ".join(f"`{f}`" for f in used_by)
    summary = (
        f"Values of `{domain.name}` that apply to the FIRM Database, each as the "
        f"data stores it. Used by {fields}."
    )
    if len(legacy) == 1:
        summary += (
            " The last is a legacy value: common in the data, not in the reference."
        )
    elif legacy:
        summary += (
            f" The last {len(legacy)} are legacy values: common in the data, not in "
            "the reference."
        )
    lines = [
        f"class {domain.class_name}(str, DocumentedEnum):",
        docstring(summary, "    "),
        "",
    ]
    for name, value in zip(names, domain.values, strict=True):
        lines.append(
            f"    {name} = {literal(value.value)}, {literal(member_doc(value))}"
        )
    for name, (legacy_value, entries) in zip(legacy_names, legacy.items(), strict=True):
        doc = legacy_doc(entries, reader)
        lines.append(f"    {name} = {literal(legacy_value)}, {literal(doc)}")
    return RenderedEnum(
        "\n".join(lines), [f"{domain.class_name}.{n}" for n in legacy_names]
    )


def render_enums(reader: SpecReader) -> str:
    used: dict[str, list[str]] = {}
    for layer in LAYERS:
        for field in reader.reference_table(layer.table).fields:
            if field.domain:
                used.setdefault(field.domain, []).append(f"{layer.table}.{field.name}")
    domains = sorted((reader.domain(d) for d in used), key=lambda d: d.class_name)
    rendered = [render_enum(d, used[d.name], reader) for d in domains]
    legacy = [m for r in rendered for m in r.legacy_members]
    return "\n".join(
        [
            '"""Coded-value domains from the Domain Tables Technical Reference.',
            "",
            HEADER,
            "",
            "Each member's value is the text the NFHL stores, unchanged: the",
            "reference's FIRM description, not its code. The service, the",
            "state file geodatabases and the county shapefiles all hold that text",
            "and declare no coded-value domains. Each member's description says",
            "what the value means, from the reference, and its code.",
            "",
            "Members whose description begins `Legacy:` are values the reference",
            "does not list but the data commonly holds (spec/legacy.json). They",
            "validate, and the models raise a `nfhl.legacy.LegacyValueWarning`.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from enum import Enum",
            "",
            "from overture.schema.system.doc import DocumentedEnum",
            "",
            f"REFERENCE_EDITION = {literal(reader.edition)}",
            "",
            "",
            "\n\n\n".join(r.source for r in rendered),
            "",
            "",
            "# Members the reference does not list; each use raises a warning.",
            "LEGACY_MEMBERS: frozenset[Enum] = frozenset(",
            "    {",
            *(f"        {m}," for m in legacy),
            "    }",
            ")",
            "",
        ]
    )


def check_types(table: str, ref: ReferenceField, svc: ServiceField | None) -> None:
    if svc is not None and ESRI_TYPES.get(svc.esri_type) != ref.type:
        raise ValueError(
            f"{table}.{ref.name}: reference says {ref.type}, service {svc.esri_type}"
        )
    if ref.type not in PYTHON_TYPES:
        raise NotImplementedError(f"{table}.{ref.name}: type {ref.type}")


def render_field(
    layer: Layer,
    ref: ReferenceField,
    svc: ServiceField | None,
    reader: SpecReader,
    extras: list[str],
) -> list[str]:
    check_types(layer.table, ref, svc)
    comments: list[str] = []
    if ref.domain:
        base = reader.domain(ref.domain).class_name
    else:
        base = PYTHON_TYPES[ref.type]
        length = svc.length if svc is not None else ref.length
        if ref.type == "Text" and length is not None:
            base = f"Annotated[{base}, MaxLen({length})]"
        if svc is not None and ref.length is not None and svc.length != ref.length:
            comments.append(
                f"Length {svc.length} on the service; the reference says {ref.length}."
            )
    annotation = base
    if extras:
        annotation = f"Annotated[{base}, {', '.join(extras)}]"
    required = ref.required and svc is not None
    if ref.required and svc is None:
        comments.append(
            "Required by the reference, and populated in the state and county "
            "downloads, but the NFHL map service does not publish it."
        )
    elif svc is None:
        comments.append("The NFHL map service does not publish it.")
    if not required:
        annotation = f"Omitable[{annotation}]"
    lines = [f"    # {line}" for c in comments for line in textwrap.wrap(c, 82)]
    lines.append(
        f"    {ref.name.lower()}: {annotation} = Field(\n"
        f"        alias={literal(ref.name)},\n"
        f"        description={literal(field_description(ref))},\n"
        "    )"
    )
    return lines


def field_description(ref: ReferenceField) -> str:
    """The reference's description, and the footnote on its requirement.

    A footnoted requirement (`R1`: "Field is applicable for BLE database") is
    not enforced, so the footnote is all the model says of it.
    """
    if ref.footnote is None:
        return ref.description
    marked = FOOTNOTED_REQUIREMENTS[ref.requirement.rstrip("0123456789")]
    footnote = f'"{ref.footnote}"'
    return f"{ref.description} {marked} in the reference, with the footnote {footnote}"


def render_service_only_field(svc: ServiceField) -> list[str]:
    """An optional field for a column the service adds and the reference lacks."""
    if svc.esri_type not in SERVICE_ONLY_TYPES:
        raise ValueError(f"{svc.name}: no Python type for {svc.esri_type}")
    base = SERVICE_ONLY_TYPES[svc.esri_type]
    if base == "str" and svc.length is not None:
        base = f"Annotated[{base}, MaxLen({svc.length})]"
    attr = re.sub(r"[^A-Za-z0-9]+", "_", svc.name).strip("_").lower()
    return [
        f"    {attr}: Omitable[{base}] = Field(\n"
        f"        alias={literal(svc.name)},\n"
        f"        description={literal(SERVICE_ONLY_DESCRIPTION)},\n"
        "    )",
        "",
    ]


def members(domain: Domain, values: Iterable[str]) -> str:
    """A tuple expression of `domain`'s enum members for `values`."""
    names = [f"{domain.class_name}.{member_name(v)}" for v in values]
    return f"({', '.join(names)},)"


def render_pair_rule(
    rule: PairRule, table: ReferenceTable, required: bool, reader: SpecReader
) -> list[str]:
    """A rule on two fields' values together, as a commented constraint decorator.

    A cross-walk rule forbids the reference subtypes its zones do not list, but
    reads in the docs as the list it allows: the shorter one, and the one the
    reference prints. A rule on a `required` field is "not when, or not
    forbidden", since `forbid_if` takes only optional fields.
    """
    when_domain = reader.domain(require_domain(table, rule.when))
    domain = reader.domain(require_domain(table, rule.field))
    field, when = literal(rule.field.lower()), literal(rule.when.lower())
    qualifier = literal(", ".join(rule.when_values))
    zones = members(when_domain, rule.when_values)
    values = members(domain, rule.forbidden)
    crosswalk = rule.licence == CROSSWALK_LICENCE
    lines = [f"# {rule.licence}"] if crosswalk else quote_comment(rule.licence)
    if rule.requires_value:
        lines.append(f"@require_if([{field}], OneOf({when}, {zones}), {qualifier})")
    elif required:
        lines.append(
            f"@require_any_true([{field}], NoneOf({when}, {zones}), "
            f"NoneOf({field}, {values}), qualifier={qualifier})"
        )
    else:
        label = ""
        if crosswalk:
            allowed = [v.value for v in domain.values if v.value not in rule.forbidden]
            text = (
                f"{rule.field.lower()} is a {domain.name} value Table 14 does not "
                f"list for {', '.join(rule.when_values)}"
            )
            text += f", which allows only {'; '.join(allowed) or 'none'}"
            label = f", label={literal(text)}"
        lines.append(
            f"@forbid_if([{field}], AllOf(OneOf({when}, {zones}), "
            f"OneOf({field}, {values}{label})), {qualifier})"
        )
    return lines


def quote_comment(quote: str) -> list[str]:
    """The licensing sentence as `#` comment lines that fit the line length."""
    return [f"# {line}" for line in textwrap.wrap(f"“{quote}”", 84)]


def render_allowed(
    allowed: Allowed, table: ReferenceTable, reader: SpecReader
) -> list[str]:
    """A limit on one field's values, as a commented constraint decorator.

    It forbids the reference values outside the limit, so a legacy value is
    left to its own warning, and is qualified by the zones its quote names: the
    field's other rule (`only_when`) is a `forbid_if` on the same field.
    """
    domain = reader.domain(require_domain(table, allowed.field))
    field = literal(allowed.field.lower())
    forbidden = reader.forbidden_values(table.name, allowed)
    zones = ", ".join(allowed.zones)
    if allowed.subtypes_of is not None:
        text = f"{allowed.field.lower()} is a {domain.name} value Table 14 does not "
        text += f"list for any of {zones}"
    else:
        text = f"{allowed.field.lower()} is a {domain.name} value other than {zones}"
    return [
        *quote_comment(allowed.quote),
        f"@forbid_if([{field}], OneOf({field}, {members(domain, forbidden)}, "
        f"label={literal(text)}), {literal(zones)})",
    ]


def require_domain(table: ReferenceTable, name: str) -> str:
    domain = table.field(name).domain
    if domain is None:
        raise ValueError(f"{table.name}.{name}: a pair rule needs a domain")
    return domain


def render_model(layer: Layer, reader: SpecReader) -> str:
    table = reader.reference_table(layer.table)
    service = reader.service_fields(layer)
    relations = reader.relationships(layer.table)

    extras: dict[str, list[str]] = {}
    for unit in relations.units:
        extras.setdefault(unit.field, []).append(f"UnitIn({literal(unit.unit_field)})")
    for datum in relations.datums:
        extras.setdefault(datum.field, []).append(
            f"DatumIn({literal(datum.datum_field)})"
        )

    decorators = []
    for only in relations.only_if:
        absent = [f"Absent({literal(f.lower())})" for f in only.any_of]
        condition = absent[0] if len(absent) == 1 else f"AllOf({', '.join(absent)})"
        decorators.append(f"@forbid_if([{literal(only.field.lower())}], {condition})")
    for zoned in relations.only_when:
        domain = reader.domain(require_domain(table, zoned.when))
        decorators.extend(quote_comment(zoned.quote))
        decorators.append(
            f"@forbid_if([{literal(zoned.field.lower())}], "
            f"NoneOf({literal(zoned.when.lower())}, {members(domain, zoned.any_of)}))"
        )
    for allowed in relations.allowed:
        decorators.extend(render_allowed(allowed, table, reader))
    for needed in relations.required_when:
        decorators.append(
            f"@require_if([{literal(needed.field.lower())}], "
            f"Populated({literal(needed.when.lower())}))"
        )
    for rule in reader.pair_rules(layer.table):
        required = table.field(rule.field).required and rule.field in service
        decorators.extend(render_pair_rule(rule, table, required, reader))

    modelled = {f.name for f in table.fields}
    unmodelled = sorted(
        name
        for name, svc in service.items()
        if name not in modelled and svc.esri_type != "esriFieldTypeGeometry"
    )
    fields: list[str] = []
    for ref in table.fields:
        fields.extend(
            render_field(
                layer, ref, service.get(ref.name), reader, extras.get(ref.name, [])
            )
        )
        fields.append("")
    if unmodelled:
        fields.append("    # Housekeeping columns only the service has.")
    for name in unmodelled:
        fields.extend(render_service_only_field(service[name]))

    enums = sorted(
        {reader.domain(f.domain).class_name for f in table.fields if f.domain}
    )
    used = "\n".join([*decorators, *fields])
    constraint_names = [n for n in CONSTRAINT_NAMES if re.search(rf"\b{n}\(", used)]
    annotation_names = [n for n in ("DatumIn", "UnitIn") if f"{n}(" in used]
    # `int64` types the feature id, which every model has.
    numeric_names = [
        "int64",
        *(n for n in ("float64", "int16") if re.search(rf"\b{n}\b", used)),
    ]
    geometry = layer_geometry(layer, reader)
    class_doc = (
        f"{reader.reference_intro(layer.table)} Published as layer "
        f"{layer.layer_id} of the NFHL MapServer, which also carries "
        f"{', '.join(f'`{n}`' for n in unmodelled)}; the reference does not "
        "define them, so they are optional and validated only by type."
    )
    return "\n".join(
        [
            f'"""`{layer.table}`: {reader.service_layer(layer)["name"]}.',
            "",
            HEADER,
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Annotated",
            "",
            "from annotated_types import MaxLen",
            "from overture.schema.system.feature import Feature",
            "from overture.schema.system.geometric import (",
            "    Geometry,",
            "    GeometryType,",
            "    GeometryTypeConstraint,",
            ")",
            *import_lines("overture.schema.system.numeric", numeric_names),
            "from overture.schema.system.optionality import Omitable",
            "from pydantic import ConfigDict, Field, model_validator",
            "",
            *import_lines("nfhl.annotations", annotation_names),
            *import_lines(
                "nfhl.constraints", [*constraint_names, "drop_null_encodings"]
            ),
            "from nfhl.legacy import warn_on_legacy_values",
            "from nfhl.models.enums import (",
            *(f"    {e}," for e in ["LEGACY_MEMBERS", "REFERENCE_EDITION", *enums]),
            ")",
            "",
            "",
            *decorators,
            f"class {layer.class_name}(Feature):",
            docstring(class_doc, "    "),
            "",
            "    model_config = ConfigDict(",
            "        # Properties neither source defines stay extras.",
            '        extra="allow",',
            "        populate_by_name=True,",
            "        serialize_by_alias=True,",
            "    )",
            "",
            '    # The reference\'s null encodings ("" and -9999) mean not populated.',
            '    _drop_null_encodings = model_validator(mode="before")(',
            "        staticmethod(drop_null_encodings)",
            "    )",
            "",
            "    # A value the reference does not list but the data commonly holds",
            "    # validates, with a LegacyValueWarning.",
            '    _warn_on_legacy_values = model_validator(mode="after")(',
            "        warn_on_legacy_values(LEGACY_MEMBERS, REFERENCE_EDITION)",
            "    )",
            "",
            *(f"    # {line}" for line in textwrap.wrap(geometry.comment, 82)),
            "    geometry: Annotated[",
            "        Geometry,",
            "        GeometryTypeConstraint(",
            f"            {', '.join(f'GeometryType.{t}' for t in geometry.types)}",
            "        ),",
            f"        Field(description={literal(geometry.description)}),",
            "    ]",
            "",
            "    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON",
            "    # output writes the service's integer OBJECTID here.",
            "    id: Omitable[int64] = Field(  # type: ignore[assignment]",
            f"        description={literal(id_description(table))},",
            "    )",
            "",
            *fields,
        ]
    )


@dataclass(frozen=True, slots=True)
class LayerGeometry:
    """What a layer's features may be, from the reference's introduction to it.

    `esri_type` is the service's `geometryType` the types must agree with.
    """

    esri_type: str
    types: tuple[str, ...]  # `GeometryType` member names
    comment: str
    description: str


# The reference describes the geometry only in each table's introduction.
GEOMETRIES = {
    "S_Fld_Haz_Ar": LayerGeometry(
        "esriGeometryPolygon",
        ("POLYGON", "MULTI_POLYGON"),
        "A multipart zone is one feature: MultiPolygon as well as Polygon.",
        "Extent of the flood zone: in the reference's words, one polygon for each "
        "contiguous flood zone designated.",
    ),
    "S_BFE": LayerGeometry(
        "esriGeometryPolyline",
        ("LINE_STRING",),
        "“Each BFE is represented by a single line with no pseudo-nodes”, so a "
        "LineString, though the service's polyline type admits several parts.",
        "The BFE line: in the reference's words, a single line extending from "
        "Special Flood Hazard Area (SFHA) boundary to SFHA boundary.",
    ),
    "S_XS": LayerGeometry(
        "esriGeometryPolyline",
        ("LINE_STRING",),
        "“The spatial entities representing cross sections are lines”, one to a "
        "feature: Table 4 holds S_XS to “Must Be Single Part”, so a LineString.",
        "The cross section line: in the reference's words, the spatial entities "
        "representing cross sections are lines.",
    ),
    "S_Profil_Basln": LayerGeometry(
        "esriGeometryPolyline",
        ("LINE_STRING",),
        "Table 4 holds S_Profil_Basln to “Must Be Single Part”, so a LineString, "
        "though the service's polyline type admits several parts.",
        "The profile baseline: in the reference's words, the location of a "
        "profile baseline or stream centerline feature for the Flood Risk Project "
        "area.",
    ),
    "S_Stn_Start": LayerGeometry(
        "esriGeometryPoint",
        ("POINT",),
        "“These locations indicate the reference point that was used as the "
        "origin”, so a Point, as the service's point type is: Esri publishes "
        "several points as esriGeometryMultipoint.",
        "The station starting location: in the reference's words, the reference "
        "point that was used as the origin for distance measurements along streams "
        "and rivers.",
    ),
}


def layer_geometry(layer: Layer, reader: SpecReader) -> LayerGeometry:
    if layer.table not in GEOMETRIES:
        raise ValueError(f"{layer.table}: say what its features are in GEOMETRIES")
    geometry = GEOMETRIES[layer.table]
    published = reader.service_layer(layer)["geometryType"]
    if published != geometry.esri_type:
        raise ValueError(
            f"{layer.table}: modelled as {geometry.esri_type}, service has {published}"
        )
    return geometry


def id_description(table: ReferenceTable) -> str:
    """The feature id's description, naming the table's own key: the field the
    reference describes as its "Primary key"."""
    (key,) = (f for f in table.fields if f.description.startswith("Primary key"))
    return (
        "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the "
        "feature id. It numbers rows in one copy of the service and identifies "
        f"nothing beyond it; the reference's key is {key.name}, assigned within "
        "one FIRM Database (one DFIRM_ID)."
    )


def import_lines(module: str, names: list[str]) -> list[str]:
    """`from module import names`, in the order ruff's isort keeps them, or
    nothing for no names; ruff format lays it out."""
    if not names:
        return []
    ordered = ", ".join(sorted(names, key=lambda n: (not n[:1].isupper(), n)))
    return [f"from {module} import {ordered}"]


def render_init(layers: Iterable[Layer]) -> str:
    imports = sorted(
        f"from nfhl.models.{lyr.module} import {lyr.class_name}" for lyr in layers
    )
    names = sorted(lyr.class_name for lyr in LAYERS)
    return "\n".join(
        [
            '"""Pydantic models for the NFHL, one per modelled service layer.',
            "",
            HEADER,
            '"""',
            "",
            "from __future__ import annotations",
            "",
            *imports,
            "",
            f"__all__ = [{', '.join(json.dumps(n) for n in names)}]",
            "",
        ]
    )


def render(reader: SpecReader | None = None) -> list[ModelFile]:
    reader = reader or SpecReader()
    files = [
        ModelFile("__init__.py", render_init(LAYERS)),
        ModelFile("enums.py", render_enums(reader)),
    ]
    files += [
        ModelFile(f"{lyr.module}.py", render_model(lyr, reader)) for lyr in LAYERS
    ]
    return files


def generate(
    out_dir: Path = MODELS_DIR, reader: SpecReader | None = None
) -> list[Path]:
    """Rewrite `out_dir` from the snapshot, formatted by ruff."""
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    written = []
    for model_file in render(reader):
        path = out_dir / model_file.path
        path.write_text(model_file.source)
        written.append(path)
    ruff = shutil.which("ruff")
    if ruff is None:
        raise RuntimeError("ruff not on PATH; run through `uv run`")
    subprocess.run([ruff, "format", "--quiet", str(out_dir)], check=True)
    return written
