"""Generate the models in `nfhl.models` from the pinned spec/ snapshot.

Unlike gatis, whose bootstrap writes once and then hands the models over, these
are a build artifact: every file under `src/nfhl/models/` is rewritten on each
run, and `tests/test_codegen.py` regenerates into a temporary directory and
asserts there is no diff. Anything a model needs to say that the snapshot does
not is said in `spec/repairs.json` or `spec/relationships.json`, each entry
quoting its licence from the reference, so it survives regeneration and stays
traceable.

What comes from where:

* field set, order, meaning, requirement and domain -- the FIRM Database
  Technical Reference (`ReferenceTable`);
* Esri type and text length -- the NFHL service, which is what is published;
  the reference's own type is cross-checked and a disagreement raises;
* allowed values -- the Domain Tables Technical Reference, after repairs;
* unit, datum and populated-only-if relationships -- `spec/relationships.json`.
"""

from __future__ import annotations

import json
import keyword
import re
import shutil
import subprocess
import textwrap
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from nfhl.spec_source import (
    LAYERS,
    Domain,
    DomainValue,
    Layer,
    ReferenceField,
    ServiceField,
    SpecReader,
)

MODELS_DIR = Path(__file__).resolve().parent / "models"

HEADER = (
    "GENERATED by `scripts/generate-models` from the pinned spec/ snapshot. Do not\n"
    "edit: change spec/repairs.json, spec/relationships.json or `nfhl.codegen`,\n"
    "then regenerate."
)

# The reference's type names against the service's. A field whose two sources
# disagree is a defect to look at, not one to resolve by picking a side.
ESRI_TYPES = {
    "esriFieldTypeString": "Text",
    "esriFieldTypeDouble": "Double",
    "esriFieldTypeSingle": "Float",
    "esriFieldTypeInteger": "Long Integer",
    "esriFieldTypeSmallInteger": "Short Integer",
    "esriFieldTypeDate": "Date",
}
PYTHON_TYPES = {"Text": "str", "Double": "float64"}

WIDTH = 70  # string chunk width before ruff format lays the code out


@dataclass(frozen=True, slots=True)
class ModelFile:
    path: str
    source: str


def literal(text: str) -> str:
    """A Python string literal for `text`, split into chunks ruff will wrap."""
    chunks = textwrap.wrap(
        text,
        WIDTH,
        break_long_words=False,
        break_on_hyphens=False,
        drop_whitespace=False,
    ) or [""]
    parts = [json.dumps(c, ensure_ascii=False) for c in chunks]
    return parts[0] if len(parts) == 1 else "(" + " ".join(parts) + ")"


def docstring(text: str, indent: str) -> str:
    if '"""' in text or "\\" in text:
        raise ValueError(f"cannot render as a docstring: {text!r}")
    body = textwrap.fill(text, 84 - len(indent), break_on_hyphens=False)
    lines = body.splitlines()
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""'
    joined = "\n".join(f"{indent}{line}" if line else "" for line in lines)
    return f'{indent}"""{joined.lstrip()}\n{indent}"""'


def member_name(value: str) -> str:
    name = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
    if not name or name[0].isdigit():
        name = f"V_{name}"
    return f"{name}_" if keyword.iskeyword(name.lower()) else name


def member_doc(value: DomainValue) -> str:
    """What a stored value means, in the reference's own words, then its code."""
    parts = [
        f"{text.rstrip('.')}."
        for text in (value.meaning, value.when_used, *value.footnotes)
        if text
    ]
    parts.append(f"Coded value `{value.code}`.")
    if value.published != value.value:
        parts.append(f"Printed in the reference as `{value.published}`.")
    return " ".join(parts)


def render_enum(domain: Domain, used_by: list[str]) -> str:
    names = [member_name(v.value) for v in domain.values]
    if len(set(names)) != len(names):
        raise ValueError(f"{domain.name}: member names collide: {names}")
    fields = ", ".join(f"`{f}`" for f in used_by)
    lines = [
        f"class {domain.class_name}(str, DocumentedEnum):",
        docstring(
            f"Values of `{domain.name}` that apply to the FIRM Database, each as "
            f"the data stores it. Used by {fields}.",
            "    ",
        ),
        "",
    ]
    for name, value in zip(names, domain.values, strict=True):
        lines.append(
            f"    {name} = {literal(value.value)}, {literal(member_doc(value))}"
        )
    return "\n".join(lines)


def render_enums(reader: SpecReader) -> str:
    used: dict[str, list[str]] = {}
    for layer in LAYERS:
        for field in reader.reference_table(layer.table).fields:
            if field.domain:
                used.setdefault(field.domain, []).append(f"{layer.table}.{field.name}")
    domains = sorted((reader.domain(d) for d in used), key=lambda d: d.class_name)
    blocks = [render_enum(d, used[d.name]) for d in domains]
    return "\n".join(
        [
            '"""Coded-value domains from the Domain Tables Technical Reference.',
            "",
            HEADER,
            "",
            "Each member's value is the text the NFHL stores, unchanged: the",
            "reference's FIRM description, not its coded value. The service, the",
            "state file geodatabases and the county shapefiles all hold that text",
            "and declare no coded-value domains. Each member's description says",
            "what the value means, from the reference, and gives its coded value.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from overture.schema.system.doc import DocumentedEnum",
            "",
            "",
            "\n\n\n".join(blocks),
            "",
        ]
    )


def check_types(table: str, ref: ReferenceField, svc: ServiceField | None) -> None:
    if svc is not None and ESRI_TYPES.get(svc.esri_type) != ref.type:
        raise ValueError(
            f"{table}.{ref.name}: reference says {ref.type}, service {svc.esri_type}"
        )
    if ref.type not in PYTHON_TYPES:
        raise NotImplementedError(f"{table}.{ref.name}: type {ref.type}")


def render_field(
    layer: Layer,
    ref: ReferenceField,
    svc: ServiceField | None,
    reader: SpecReader,
    extras: list[str],
) -> list[str]:
    check_types(layer.table, ref, svc)
    comments: list[str] = []
    if ref.domain:
        base = reader.domain(ref.domain).class_name
    else:
        base = PYTHON_TYPES[ref.type]
        length = svc.length if svc is not None else ref.length
        if ref.type == "Text" and length is not None:
            base = f"Annotated[{base}, MaxLen({length})]"
        if svc is not None and ref.length is not None and svc.length != ref.length:
            comments.append(
                f"Length {svc.length} on the service; the reference says {ref.length}."
            )
    annotation = base
    if extras:
        annotation = f"Annotated[{base}, {', '.join(extras)}]"
    required = ref.required and svc is not None
    if ref.required and svc is None:
        comments.append(
            "Required by the reference, and populated in the state and county "
            "downloads, but the NFHL map service does not publish it."
        )
    if not required:
        annotation = f"Omitable[{annotation}]"
    lines = [f"    # {line}" for c in comments for line in textwrap.wrap(c, 82)]
    lines.append(
        f"    {ref.name.lower()}: {annotation} = Field(\n"
        f"        alias={literal(ref.name)},\n"
        f"        description={literal(ref.description)},\n"
        "    )"
    )
    return lines


def render_model(layer: Layer, reader: SpecReader) -> str:
    table = reader.reference_table(layer.table)
    service = reader.service_fields(layer)
    relations = reader.relationships(layer.table)

    extras: dict[str, list[str]] = {}
    for unit in relations.units:
        extras.setdefault(unit.field, []).append(f"UnitIn({literal(unit.unit_field)})")
    for datum in relations.datums:
        extras.setdefault(datum.field, []).append(
            f"DatumIn({literal(datum.datum_field)})"
        )

    decorators = []
    for only in relations.only_if:
        absent = [f"Absent({literal(f.lower())})" for f in only.any_of]
        condition = absent[0] if len(absent) == 1 else f"AllOf({', '.join(absent)})"
        decorators.append(f"@forbid_if([{literal(only.field.lower())}], {condition})")
    for needed in relations.required_when:
        decorators.append(
            f"@require_if([{literal(needed.field.lower())}], "
            f"Populated({literal(needed.when.lower())}))"
        )

    modelled = {f.name for f in table.fields}
    unmodelled = sorted(
        name
        for name, svc in service.items()
        if name not in modelled and svc.esri_type != "esriFieldTypeGeometry"
    )
    fields: list[str] = []
    for ref in table.fields:
        fields.extend(
            render_field(
                layer, ref, service.get(ref.name), reader, extras.get(ref.name, [])
            )
        )
        fields.append("")

    enums = sorted(
        {reader.domain(f.domain).class_name for f in table.fields if f.domain}
    )
    class_doc = (
        f"{reader.reference_intro(layer.table)} Published as layer "
        f"{layer.layer_id} of the NFHL MapServer, which also carries "
        f"{', '.join(f'`{n}`' for n in unmodelled)}; the reference does not "
        "define them, so they arrive as extra properties."
    )
    return "\n".join(
        [
            f'"""`{layer.table}`: {reader.service_layer(layer)["name"]}.',
            "",
            HEADER,
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Annotated",
            "",
            "from annotated_types import MaxLen",
            "from overture.schema.system.feature import Feature",
            "from overture.schema.system.geometric import (",
            "    Geometry,",
            "    GeometryType,",
            "    GeometryTypeConstraint,",
            ")",
            "from overture.schema.system.numeric import float64, int64",
            "from overture.schema.system.optionality import Omitable",
            "from pydantic import ConfigDict, Field, model_validator",
            "",
            "from nfhl.annotations import DatumIn, UnitIn",
            "from nfhl.constraints import (",
            "    Absent,",
            "    AllOf,",
            "    Populated,",
            "    drop_null_encodings,",
            "    forbid_if,",
            "    require_if,",
            ")",
            f"from nfhl.models.enums import {', '.join(enums)}",
            "",
            "",
            *decorators,
            f"class {layer.class_name}(Feature):",
            docstring(class_doc, "    "),
            "",
            "    model_config = ConfigDict(",
            "        # Service-only fields (OBJECTID, GlobalID, ...) stay as extras.",
            '        extra="allow",',
            "        populate_by_name=True,",
            "        serialize_by_alias=True,",
            "    )",
            "",
            '    # The reference\'s null encodings ("" and -9999) mean not populated.',
            '    _drop_null_encodings = model_validator(mode="before")(',
            "        staticmethod(drop_null_encodings)",
            "    )",
            "",
            "    # A multipart zone is one feature: MultiPolygon as well as Polygon.",
            "    geometry: Annotated[",
            "        Geometry,",
            "        GeometryTypeConstraint(",
            "            GeometryType.POLYGON, GeometryType.MULTI_POLYGON",
            "        ),",
            "    ]",
            "",
            "    # Redeclared from `Feature`, where it is a string: ArcGIS's GeoJSON",
            "    # output writes the service's integer OBJECTID here.",
            "    id: Omitable[int64] = Field(  # type: ignore[assignment]",
            f"        description={literal(ID_DESCRIPTION)},",
            "    )",
            "",
            *fields,
        ]
    )


ID_DESCRIPTION = (
    "The service's OBJECTID, which ArcGIS's GeoJSON output writes as the feature "
    "id. It numbers rows in one copy of the service and identifies nothing beyond "
    "it; the reference's key is FLD_AR_ID, assigned within one FIRM Database "
    "(one DFIRM_ID)."
)


def render_init(layers: Iterable[Layer]) -> str:
    imports = [
        f"from nfhl.models.{lyr.module} import {lyr.class_name}" for lyr in layers
    ]
    names = sorted(lyr.class_name for lyr in LAYERS)
    return "\n".join(
        [
            '"""Pydantic models for the NFHL, one per modelled service layer.',
            "",
            HEADER,
            '"""',
            "",
            "from __future__ import annotations",
            "",
            *imports,
            "",
            f"__all__ = [{', '.join(json.dumps(n) for n in names)}]",
            "",
        ]
    )


def render(reader: SpecReader | None = None) -> list[ModelFile]:
    reader = reader or SpecReader()
    files = [
        ModelFile("__init__.py", render_init(LAYERS)),
        ModelFile("enums.py", render_enums(reader)),
    ]
    files += [
        ModelFile(f"{lyr.module}.py", render_model(lyr, reader)) for lyr in LAYERS
    ]
    return files


def generate(
    out_dir: Path = MODELS_DIR, reader: SpecReader | None = None
) -> list[Path]:
    """Rewrite `out_dir` from the snapshot, formatted by ruff."""
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    written = []
    for model_file in render(reader):
        path = out_dir / model_file.path
        path.write_text(model_file.source)
        written.append(path)
    ruff = shutil.which("ruff")
    if ruff is None:
        raise RuntimeError("ruff not on PATH; run through `uv run`")
    subprocess.run([ruff, "format", "--quiet", str(out_dir)], check=True)
    return written
